# spring:
#   application:
#     name: hello-mongodb-boot
#   data:
#     jpa:
#       repositories:
#         enabled: true
#     mongodb:
#       host: @server-ip-or-fullname@
#       port: 27017
#       database: lukedb
#       # username: luke
#       # password: luke
#       username: ENC(zjpIoh+5DcY+QGRUOxINeA==)
#       password: ENC(DIM8/d6v+5pS57wfdRfgaA==)

# MongoDB
# spring.data.mongodb.uri: mongodb://@server-ip-or-fullname@:27017 <======== Do **NOT** use uri. jasypt does not work for uri.
spring.data.mongodb.host: @server-ip-or-fullname@
spring.data.mongodb.port: 27017
spring.data.mongodb.database: lukedb
# spring.data.mongodb.username: luke
# spring.data.mongodb.password: luke
spring.data.mongodb.username: ENC(zjpIoh+5DcY+QGRUOxINeA==)
spring.data.mongodb.password: ENC(DIM8/d6v+5pS57wfdRfgaA==)
