SELECT
    COUNT(pool.INVESTOR_ID),
    lp.PROPERTY_ID
FROM
    T_CMSA_POOL pool,
    T_CMSA_LOAN_PROPERTY lp
WHERE
    pool.LOAN_ID = lp.LOAN_ID
GROUP BY
    lp.PROPERTY_ID
HAVING
    COUNT(pool.INVESTOR_ID) > 1