--ALTER TABLE T_CMSA_INT_ON_ADVANCE MODIFY (INTEREST_DAYS NUMBER(3));

--ALTER TABLE T_CMSA_INT_ON_ADVANCE add tmp_INTEREST_DAYS NUMBER(3);

--update T_CMSA_INT_ON_ADVANCE set tmp_INTEREST_DAYS = INTEREST_DAYS;

--update T_CMSA_INT_ON_ADVANCE set INTEREST_DAYS = null;

--ALTER TABLE T_CMSA_INT_ON_ADVANCE MODIFY (INTEREST_DAYS NUMBER(3));

--update T_CMSA_INT_ON_ADVANCE set INTEREST_DAYS = tmp_INTEREST_DAYS;

ALTER TABLE T_CMSA_INT_ON_ADVANCE DROP COLUMN tmp_INTEREST_DAYS;




