SELECT
    Pool.Investor_Id, -- AS "Investor Number",
     Lp.Loan_Id, --       AS "Loan Id",
   -- lp.PROPERTY_ID, --   AS "Property Number",
    lp.PROPERTY_SEQ_NO as "Property_Number",   
    lp.PROSPECTUS_PROPERTY_ID,
    p.ADDRESS,
    p.CITY,
    p.COUNTY,
    p.STATE,
    p.ZIP_CODE,
    pt.DESCRIPTION AS "PROPERTY_TYPE_DESCRIPTION",
    pa.APPRAISAL_VALUE,
    pa.APPRAISAL_DT,
    p.APPRAISAL_VALUE_CONTRIBUTION,
    p.YEAR_BUILT,
    p.NET_SQRFT_CONTRIBUTION,
    p.TOTAL_UNITS_CONTRIBUTION,
    p.GROUND_LEASE_FLAG,
    p.LAST_RENO_YEAR,
    p.NAME AS "PROJECT_NAME",
    Lp.Allocated_Percnt_Current
   -- P.NET_SQRFT_CONTRIBUTION   AS "COMMERCIAL_NRA",
  --  P.NET_SQRFT_CONTRIBUTION   AS "RESIDENTIAL_NRA",
  --  p.TOTAL_UNITS_CONTRIBUTION AS "TOTAL_BEDROOMS"
  
FROM
    T_CMSA_LOAN_PROPERTY lp,
    T_CMSA_PROPERTY_CODE pc,
    T_CMSA_PROPERTY_TYPE pt,
    T_CMSA_POOL pool,
    T_CMSA_PROPERTY p
LEFT OUTER JOIN
    T_CMSA_PROPERTY_APPRAISAL pa
ON
    pa.PROPERTY_ID = p.PROPERTY_ID
WHERE
    lp.PROPERTY_ID = p.PROPERTY_ID
AND p.PROPERTY_CD = pc.PROPERTY_CD
AND pc.PROPERTY_TYPE = pt.PROPERTY_TYPE
AND pool.LOAN_ID = lp.LOAN_ID
Order By
    1,2,3
