DECLARE
  IN_NINVESTORID NUMBER;
  IN_NREPMONTH NUMBER;
  IN_NREPYEAR NUMBER;
  OUT_DASOFDT VARCHAR2(200);
  OUT_NSTATUSCODE NUMBER;
  OUT_CVGENERIC SYS_REFCURSOR;
BEGIN
  IN_NINVESTORID := 571;
  IN_NREPMONTH := 4;
  IN_NREPYEAR := 2012;
  OUT_CVGENERIC := NULL;

  SP_CMSA_REPORTS_PERIODICLOAN(
    IN_NINVESTORID => IN_NINVESTORID,
    IN_NREPMONTH => IN_NREPMONTH,
    IN_NREPYEAR => IN_NREPYEAR,
    OUT_DASOFDT => OUT_DASOFDT,
    OUT_NSTATUSCODE => OUT_NSTATUSCODE,
    OUT_CVGENERIC => OUT_CVGENERIC
  );
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('OUT_DASOFDT = ' || OUT_DASOFDT);
*/ 
  :OUT_DASOFDT := OUT_DASOFDT;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('OUT_NSTATUSCODE = ' || OUT_NSTATUSCODE);
*/ 
  :OUT_NSTATUSCODE := OUT_NSTATUSCODE;
  /* Legacy output: 
DBMS_OUTPUT.PUT_LINE('OUT_CVGENERIC = ' || OUT_CVGENERIC);
*/ 
  :OUT_CVGENERIC := OUT_CVGENERIC; --<-- Cursor
END;
