SET serveroutput ON format wrapped;
DECLARE
  IN_NINVESTORID  NUMBER ;
  IN_NREPMONTH    NUMBER ;
  IN_NREPYEAR     NUMBER ;
  OUT_NSTATUSCODE NUMBER;
  --TYPE ref_cursor IS  REF  CURSOR;
  OUT_CVGENERIC PKG_CMSA_COMMDEFI.GENCURTYP;
BEGIN
  --
  --
  IN_NINVESTORID := 769;
  IN_NREPMONTH   := 11;
  IN_NREPYEAR    := 2012;
  --
  EXEC SP_CMSA_REPORTS_WATCHLIST(IN_NINVESTORID, IN_NREPMONTH, IN_NREPYEAR, OUT_NSTATUSCODE, OUT_CVGENERIC);
  --PRINT OUT_CVGENERIC;
  --
  --
END;