--ANALYZE INDEX XPKT_CMSA_INVESTOR COMPUTE STATISTICS ;
--select * from dba_indexes;
--
ANALYZE INDEX XPKT_CMSA_pool VALIDATE STRUCTURE;
SELECT lf_blks, del_lf_rows FROM index_stats;
--
--ALTER INDEX XPKT_CMSA_INVESTOR REBUILD;
