SELECT
    PROPERTY_ID,
    DATA_TYPE AS AN,
    NOI       AS AN_NOI,
    NULL      AS YTD,
    NULL      AS YTD_NOI
FROM
    T_CMSA_FINANCIAL_SUMMARY
WHERE
    PROPERTY_ID IN (804,816,904)
AND STATEMENT_PERIOD = 2011
AND DATA_TYPE = 'AN'
UNION
SELECT
    PROPERTY_ID,
    NULL      AS AN,
    NULL      AS AN_NOI,
    DATA_TYPE AS YTD,
    NOI       AS YTD_NOI
FROM
    T_CMSA_FINANCIAL_SUMMARY
WHERE
    PROPERTY_ID IN (804,816,904)
AND STATEMENT_PERIOD = 2011
AND DATA_TYPE = 'YTD'