SELECT
    i.INVESTOR_ID,
    --i.INVESTOR_NAME ,
    rt.RULE_TYPE,
    rt.DESCRIPTION,
    ra.ATTR_NAME,
    --ra.ATTR_CODE,
    br.RULE_CODE,
    br.DESCRIPTION,
    i.SWAP_PAYMENT_FLAG
FROM
    T_CMSA_INVESTOR i,
    T_CMSA_INVESTOR_RULE ir,
    T_CMSA_RULE_TYPE rt,
    T_CMSA_RULE_ATTRIBUTE ra,
    T_CMSA_RULE_MATRIX rm,
    T_CMSA_BUSINESS_RULE br
WHERE
    ra.RULE_ID = rm.RULE_ID
AND rm.RULE_TYPE = rt.RULE_TYPE
AND i.INVESTOR_ID = ir.INVESTOR_ID
AND ir.RULE_TYPE = rm.RULE_TYPE
AND ir.RULE_ID = rm.RULE_ID
AND br.RULE_ID = ra.RULE_ID
AND i.INVESTOR_ID = 627;
--AND ir.RULE_ID = 3