-- T29 No data
SELECT
    AR.INVESTOR_ID,
    AR.LOAN_ID,
    DECODE(PIAdv.Advance_Dt,NULL,0-PKG_CMSA_REPORTS_REMITTANCE.SP_CMSA_CalcLateASERPmt_FNC
    (AR.INVESTOR_ID, AR.LOAN_ID, PIR.RECOVERY_DT, TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE, 'YYYY')) ,
    DECODE(Q1.Rule_Code,0,0,1,(PKG_CMSA_Reports_RemitSuppTab.SP_CMSA_FindASER_FNC
    (PIAdv.Investor_Id,PIAdv.Loan_ID,PIAdv.Advance_Dt)-
    PKG_CMSA_REPORTS_REMITTANCE.SP_CMSA_CalcLateASERPmt_FNC(AR.INVESTOR_ID, AR.LOAN_ID,
    PIADV.ADVANCE_DT, TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'YYYY')) ),ROUND((NVL
    (PIAdv.Principal_Advance,0) + NVL(PIAdv.Net_Interest,0)) * NVL(PIAdv.ASER_Percnt,0) -
    PKG_CMSA_REPORTS_REMITTANCE.SP_CMSA_CalcLateASERPmt_FNC(AR.INVESTOR_ID, AR.LOAN_ID,
    PIADV.ADVANCE_DT, TO_CHAR(SYSDATE,'MM'),TO_CHAR(SYSDATE,'YYYY')) ,2))) AS ASERAMT,
    PKG_CMSA_Reports_Remittance.SP_CMSA_CumASERBalance_FNC(AR.INVESTOR_ID,AR.LOAN_ID, TO_CHAR
    (SYSDATE,'MM'),TO_CHAR(SYSDATE,'YYYY')) CumASER
FROM
    T_CMSA_LOAN_ARA AR,
    -- replace with T_CMSA_LOAN_ASER 05/05/06
    -- T_CMSA_APPRAISAL_REDUCTION AR,
    T_CMSA_POOL P,
    T_CMSA_PI_ADVANCE PIAdv,
    -- Replace T_CMSA_APPRAISAL_REDUCTION WITH T_CMSA_LOAN_ARA 05/05/06
    (
        SELECT
            INVESTOR_ID,
            LOAN_ID,
            MAX(AR.ARA_DT) ARA_DT
        FROM
            T_CMSA_LOAN_ARA AR
            --T_CMSA_APPRAISAL_REDUCTION AR
        WHERE
            AR.ARA_DT <= PKG_CMSA_Functions.Sp_Cmsa_Repdeterdt_Fnc(AR.INVESTOR_ID,TO_CHAR (SYSDATE,
            'MM'),TO_CHAR(SYSDATE,'YYYY'))
        GROUP BY
            INVESTOR_ID,
            LOAN_ID) Q,
    (
        SELECT
            IR.INVESTOR_ID ,
            BR.Rule_Code
        FROM
            T_CMSA_INVESTOR_RULE IR,
            T_CMSA_BUSINESS_RULE BR
        WHERE
            IR.Rule_Type = 1
        AND IR.Rule_Id = BR.Rule_Id )Q1,
    T_CMSA_PI_RECOVERY PIR
WHERE
    AR.INVESTOR_ID=P.INVESTOR_ID
AND AR.INVESTOR_ID=Q1.INVESTOR_ID
AND AR.LOAN_ID=P.LOAN_ID
AND AR.INVESTOR_ID=Q.INVESTOR_ID
AND AR.LOAN_ID=Q.LOAN_ID
AND AR.ARA_DT=Q.ARA_DT
AND PKG_CMSA_Reports_Remittance.SP_CMSA_Status_BeginDt_FNC(AR.INVESTOR_ID,AR.LOAN_ID, TO_CHAR
    (SYSDATE,'MM'),TO_CHAR(SYSDATE,'YYYY')) IS NOT NULL
AND PIAdv.Investor_Id = AR.INVESTOR_ID
AND PIAdv.Loan_Id = AR.LOAN_ID
AND PIAdv.Advance_Dt =
    (
        SELECT
            MAX(PI.Advance_Dt)
        FROM
            T_CMSA_PI_ADVANCE PI
        WHERE
            PI.Investor_Id = AR.INVESTOR_ID
        AND PI.Loan_Id = AR.LOAN_ID
        AND PI.Advance_Dt <= PKG_CMSA_Functions.Sp_Cmsa_Trusteeremitdt_Fnc(PI.INVESTOR_ID, TO_CHAR
            (SYSDATE,'MM'),TO_CHAR(SYSDATE,'YYYY')))
AND PIAdv.LOAN_ID = PIR.LOAN_ID(+)
AND PIAdv.INVESTOR_ID = PIR.INVESTOR_ID(+)
AND PIAdv.PAYMENT_DUE_DT = PIR.PAYMENT_DUE_DT(+)