SELECT
    V_CMSA_FINANCIAL_SUMMARY.LOAN_ID,
    V_CMSA_FINANCIAL_SUMMARY.PROPERTY_NUMBER,
    V_CMSA_FINANCIAL_SUMMARY.DATA_TYPE,
    V_CMSA_FINANCIAL_SUMMARY.STATEMENT_PERIOD,
    V_CMSA_FINANCIAL_SUMMARY.BEGIN_YYYYMM,
    V_CMSA_FINANCIAL_SUMMARY.END_YYYYMM,
    V_CMSA_FINANCIAL_SUMMARY.STATEMENT_TYPE,
    V_CMSA_FINANCIAL_SUMMARY.DSCR_NCF_NOTE_A,
    V_CMSA_FINANCIAL_SUMMARY.DSCR_NCF_NOTE_B,
    V_CMSA_FINANCIAL_SUMMARY.DSCR_NCF_NOTE_C
FROM
    V_CMSA_FINANCIAL_SUMMARY
WHERE
    V_CMSA_FINANCIAL_SUMMARY.DATA_TYPE = 'UB'
ORDER BY
    V_CMSA_FINANCIAL_SUMMARY.LOAN_ID,
    V_CMSA_FINANCIAL_SUMMARY.PROPERTY_NUMBER