--
SELECT
    *
FROM
    T_CMSA_PERIODIC_LOAN
WHERE
    CREATE_DT IS NOT NULL
AND TRUNC(CREATE_DT) = to_date('2012-08-09', 'yyyy-mm-dd');
--
SELECT
    *
FROM
    T_CMSA_DAILY_LOAN_FEED
WHERE
    FEED_DT IS NOT NULL
ORDER BY
    FEED_DT DESC;