SELECT
    pa.APPRAISAL_DT,
    pa.APPRAISAL_VALUE,
    p.APPRAISAL_VALUE_CONTRIBUTION,
    p.APPRAISAL_DT_CONTRIBUTION,
    pa.APPRAISAL_SOURCE,
    pa.REMARKS,
    pa.MODIFY_DT,
    pa.MODIFIED_BY
FROM
    T_CMSA_PROPERTY_APPRAISAL pa,
    T_CMSA_LOAN_PROPERTY lp,
    T_CMSA_PROPERTY p
WHERE
    pa.PROPERTY_ID = lp.PROPERTY_ID
AND p.PROPERTY_ID = lp.PROPERTY_ID
AND lp.LOAN_ID = 310903673
--AND pa.APPRAISAL_VALUE != p.APPRAISAL_VALUE_CONTRIBUTION