SELECT
    I.INVESTOR_ID,
    L.LOAN_ID,
    LP.PROPERTY_SEQ_NO,
    --LP.PROSPECTUS_PROPERTY_ID,
    PL.PROSPECTUS_LOAN_ID,
    P.PROPERTY_ID,
    L.FEE_PERIOD,
    L.OPEN_PERIOD,
    P.ADDRESS,
    P.CITY,
    P.STATE,
    P.ZIP_CODE,
    P.COUNTY,
    P.PROPERTY_CD,
    P.NET_SQRFT_CONTRIBUTION,
    P.TOTAL_UNITS_CONTRIBUTION,
    P.YEAR_BUILT,
    P.NOI_CONTRIBUTION,
    P.DSCR_NOI_CONTRIBUTION,
    P.APPRAISAL_VALUE_CONTRIBUTION,
    P.APPRAISAL_DT_CONTRIBUTION,
    P.REVENUE_CONTRIBUTION,
    P.OPR_EXPENSE_CONTRIBUTION,
    P.OCCU_DT_CONTRIBUTION,
    P.GROUND_LEASE_FLAG,
    P.NCF_CONTRIBUTION,
    P.DSCR_NCF_CONTRIBUTION,
    P.LAST_RENO_YEAR,
    L.ORIGINAL_LOAN_TERM,
    L.ORIGINAL_AMORT_TERM,
    L.ORIGINAL_NOTE_RATE,
    L.FST_PYMT_DUE_DT,
    L.GRACE_DAYS,
    L.INTEREST_ACCRUAL_CD,
    L.PAYMENT_CD,
    L.PREPYMT_LCKOUT_END_DT,
    L.YLD_MAINT_END_DT,
    L.OPEN_PRD_BEGIN_DT,
    L.PREPYMT_TRM_DESC,
    L.REMAIN_TERM_CONTRIBUTION,
    L.REMAIN_AMORT_TERM_CONTIBUTION,
    L.MATURITY_DT_CONTRIBUTION,
    L.NOTE_RATE_CONTRIBUTION,
    L.NET_RATE_CONTRIBUTION,
    L.TOT_PROPERTIES_CONTRIBUTION,
    L.CROSS_COLLA_LOAN_GRP,
    L.ESCROWS_FLAG,
    L.RESERVES_FLAG,
    L.HYPER_AMORT_BEGIN_DT,
    L.DEFEAS_END_DT,
    L.LOAN_CONTRIBUTOR ,
    L.ORIGINATION_DT ,
    L.OPEN_PERIOD,
    PL.ORIGINAL_NOTE_AMT ,
    PL.SCH_PRINCIPAL_CONTRIBUTION ,
    PL.PI_CONTRIBUTION ,
    PL.SPLIT_LOAN_ID ,
    P.NAME
FROM
    T_CMSA_POOL PL,
    T_CMSA_LOAN L,
    T_CMSA_INVESTOR I,
    T_CMSA_LOAN_PROPERTY LP,
    T_CMSA_PROPERTY P
WHERE
    PL.INVESTOR_ID = I.INVESTOR_ID
AND PL.LOAN_ID = L.LOAN_ID
AND LP.LOAN_ID = L.LOAN_ID
AND LP.PROPERTY_ID = P.PROPERTY_ID
AND I.INVESTOR_ID NOT IN ( 172,
                          174,
                          175,
                          177,
                          151,
                          153,
                          155,
                          159,
                          161,
                          163,
                          166,
                          171,
                          318,
                          511,
                          512,
                          529,
                          533,
                          534,
                          537,
                          538,
                          539,
                          540,
                          541,
                          551,
                          999 )
--AND L.LOAN_ID = 600876359