SELECT
    LOAN_ID ,
    PERIODIC_YEAR,
    PERIODIC_MONTH,
    DELINQUENT_COMMENTS
FROM
    T_CMSA_PERIODIC_LOAN
WHERE
    LOAN_ID = 170206927 --550203537
AND RTRIM(DELINQUENT_COMMENTS) IS NOT NULL
ORDER BY
    ( PERIODIC_YEAR || lpad(PERIODIC_MONTH, 2, '0')) DESC