CREATE TABLE
    CMSA_APP_USER.T_CMSA_PERIODIC_LOAN_BAK
    (
        LOAN_ID NUMBER(12) NOT NULL,
        PERIODIC_MONTH NUMBER(2) NOT NULL,
        PERIODIC_YEAR NUMBER(4) NOT NULL,
        DELINQUENT_COMMENTS_OLD VARCHAR2(4000),
        DELINQUENT_COMMENTS_NEW VARCHAR2(4000),
        BAK_DATE TIMESTAMP
    );

