CREATE OR REPLACE PROCEDURE "CMSA"."SP_CMSA_REPORT_WATCHLIST_LOAD" (
    IN_NINVESTORID  IN NUMBER,
    IN_NREPMONTH    IN NUMBER,
    IN_NREPYEAR     IN NUMBER,
    OUT_NSTATUSCODE OUT NUMBER,
    OUT_CVGENERIC IN OUT PKG_CMSA_COMMDEFI.GENCURTYP
  )
 AS
 OUT_CV_SERVICER_WATCHLIST   PKG_CMSA_COMMDEFI.GENCURTYP;
 OUT_CVGENERICTOT PKG_CMSA_COMMDEFI.GENCURTYP;
 OUT_DASOFDT   VARCHAR2(12);
 V_PREV_MONTH  NUMBER;
 V_PREV_YEAR   NUMBER;
 V_INVESTOR    NUMBER:=IN_NINVESTORID;
 -- Added by SrinivasT for Fixing error when comments are more than 2000 Characters.
 -- VARCHAR2_TABLE by default hold only 2000 characters.
 TYPE VARCHAR2_TABLE1 IS TABLE OF VARCHAR2(4000)  INDEX BY BINARY_INTEGER;

 TYPE TY_RPT_SERVICER_WATCHLIST IS RECORD
  (
    TRANSACTION_ID                 DBMS_SQL.VARCHAR2_TABLE,
    GROUP_ID                       DBMS_SQL.VARCHAR2_TABLE,
    LOAN_ID                        DBMS_SQL.NUMBER_TABLE,
    PROSPECTUS_LOAN_ID             DBMS_SQL.VARCHAR2_TABLE,
    NAME                           DBMS_SQL.VARCHAR2_TABLE,
    PROPERTY_CD                    DBMS_SQL.VARCHAR2_TABLE,
    CITY                           DBMS_SQL.VARCHAR2_TABLE,
    STATE                          DBMS_SQL.VARCHAR2_TABLE,
    EFFECTIVE_DT                   DBMS_SQL.VARCHAR2_TABLE,
    END_SCH_BAL                    DBMS_SQL.NUMBER_TABLE,
    PAID_TO_DT                     DBMS_SQL.VARCHAR2_TABLE,
    MATURITY_DT                    DBMS_SQL.VARCHAR2_TABLE,
    FISCAL_YR_DSCRNCF              DBMS_SQL.NUMBER_TABLE,
    FISCAL_YR_END_YRMM             DBMS_SQL.VARCHAR2_TABLE,
    MOST_DSCRNCF                   DBMS_SQL.VARCHAR2_TABLE,
    BEGIN_YRMM                     DBMS_SQL.VARCHAR2_TABLE,
    END_YRMM                       DBMS_SQL.VARCHAR2_TABLE,
    REFCD_CRITERIA                 DBMS_SQL.VARCHAR2_TABLE,
    -- Modified by SrinivasT for Fixing error when comments are more than 2000 Characters.
    -- VARCHAR2_TABLE by default hold only 2000 characters.
    COMMENTS                       VARCHAR2_TABLE1
);

 V_SERVICER_WATCHLIST   TY_RPT_SERVICER_WATCHLIST;
 V_COUNT  NUMBER;

 BEGIN
  OUT_NSTATUSCODE := 0;

-- Clear the existing information from the table.
SELECT COUNT(*) INTO V_COUNT FROM T_CMSA_TMP_RPT_WATCH_SRVCRCRNT WHERE INVESTOR_ID=IN_NINVESTORID;
IF V_COUNT > 0 THEN
DELETE FROM T_CMSA_TMP_RPT_WATCH_SRVCRCRNT WHERE INVESTOR_ID=IN_NINVESTORID;
END IF;

SP_CMSA_REPORTS_WATCHLIST(IN_NINVESTORID,IN_NREPMONTH,IN_NREPYEAR,OUT_DASOFDT,OUT_NSTATUSCODE,OUT_CV_SERVICER_WATCHLIST,OUT_CVGENERICTOT);
IF OUT_NSTATUSCODE <> 0 THEN
    OUT_NSTATUSCODE := 1;
    RETURN;
END IF;

FETCH OUT_CV_SERVICER_WATCHLIST
BULK COLLECT INTO
     V_SERVICER_WATCHLIST.TRANSACTION_ID,
     V_SERVICER_WATCHLIST.GROUP_ID,
     V_SERVICER_WATCHLIST.LOAN_ID,
     V_SERVICER_WATCHLIST.PROSPECTUS_LOAN_ID,
     V_SERVICER_WATCHLIST.NAME,
     V_SERVICER_WATCHLIST.PROPERTY_CD,
     V_SERVICER_WATCHLIST.CITY,
     V_SERVICER_WATCHLIST.STATE,
     V_SERVICER_WATCHLIST.EFFECTIVE_DT,
     V_SERVICER_WATCHLIST.END_SCH_BAL,
     V_SERVICER_WATCHLIST.PAID_TO_DT,
     V_SERVICER_WATCHLIST.MATURITY_DT,
     V_SERVICER_WATCHLIST.FISCAL_YR_DSCRNCF,
     V_SERVICER_WATCHLIST.FISCAL_YR_END_YRMM,
     V_SERVICER_WATCHLIST.MOST_DSCRNCF,
     V_SERVICER_WATCHLIST.BEGIN_YRMM,
     V_SERVICER_WATCHLIST.END_YRMM,
     V_SERVICER_WATCHLIST.REFCD_CRITERIA,
     V_SERVICER_WATCHLIST.COMMENTS;

FORALL I IN 1.. V_SERVICER_WATCHLIST.TRANSACTION_ID.COUNT
INSERT INTO T_CMSA_TMP_RPT_WATCH_SRVCRCRNT
(
    TRANSACTION_ID,
    GROUP_ID,
    LOAN_ID,
    PROSPECTUS_LOAN_ID,
    NAME,
    PROPERTY_CD,
    CITY,
    STATE,
    EFFECTIVE_DT,
    END_SCH_BAL,
    PAID_TO_DT,
    MATURITY_DT,
    FISCAL_YR_DSCRNCF,
    FISCAL_YR_END_YRMM,
    MOST_DSCRNCF,
    BEGIN_YRMM,
    END_YRMM,
    REFCD_CRITERIA,
    COMMENTS,
    INVESTOR_ID
)
VALUES
(
     V_SERVICER_WATCHLIST.TRANSACTION_ID(I),
     V_SERVICER_WATCHLIST.GROUP_ID(I),
     V_SERVICER_WATCHLIST.LOAN_ID(I),
     V_SERVICER_WATCHLIST.PROSPECTUS_LOAN_ID(I),
     V_SERVICER_WATCHLIST.NAME(I),
     V_SERVICER_WATCHLIST.PROPERTY_CD(I),
     V_SERVICER_WATCHLIST.CITY(I),
     V_SERVICER_WATCHLIST.STATE(I),
     V_SERVICER_WATCHLIST.EFFECTIVE_DT(I),
     V_SERVICER_WATCHLIST.END_SCH_BAL(I),
     V_SERVICER_WATCHLIST.PAID_TO_DT(I),
     V_SERVICER_WATCHLIST.MATURITY_DT(I),
     V_SERVICER_WATCHLIST.FISCAL_YR_DSCRNCF(I),
     V_SERVICER_WATCHLIST.FISCAL_YR_END_YRMM(I),
     V_SERVICER_WATCHLIST.MOST_DSCRNCF(I),
     V_SERVICER_WATCHLIST.BEGIN_YRMM(I),
     V_SERVICER_WATCHLIST.END_YRMM(I),
     V_SERVICER_WATCHLIST.REFCD_CRITERIA(I),
     V_SERVICER_WATCHLIST.COMMENTS(I),
     V_INVESTOR
);

CLOSE OUT_CV_SERVICER_WATCHLIST;

OPEN OUT_CVGENERIC FOR
SELECT
    TRANSACTION_ID,
    LOAN_ID,
    PROSPECTUS_LOAN_ID,
    EFFECTIVE_DT,
    REFCD_CRITERIA
FROM  T_CMSA_TMP_RPT_WATCH_SRVCRCRNT WHERE INVESTOR_ID=V_INVESTOR ORDER BY LOAN_ID ASC;


EXCEPTION
   WHEN OTHERS THEN
        OUT_NSTATUSCODE := 1;

      PKG_CMSA_ERRORHANDLING.SP_CMSA_LOGERRMSG ('sp_cmsa_report_watchlist_load::Error Loading::'||SQLERRM);

      PKG_CMSA_ERRORHANDLING.SP_CMSA_GETERRMSG (out_cvgeneric);

 END sp_cmsa_report_watchlist_load;
 