  SELECT t1.MACADDRESS, t3.DEVICE_MODEL, t2.PHYPORT, t4.CCPHONENUMBER, t6.CCCALLINGLINELASTNAME, t6.CCCALLINGLINEFIRSTNAME, t8.LINEPORT, CASE  WHEN
(t6.CCUSERID = ?) THEN ? ELSE ? END FROM endpoint t2 LEFT OUTER JOIN ENDPOINTADDRESS t8 ON (t8.ENDPOINT_ID = t2.ID) LEFT OUTER JOIN (ROOTENTITY t5 J
OIN CUSTOMERUSERROOT t6 ON (t6.ID = t5.ID) JOIN CUSTOMERUSER t7 ON (t7.ID = t5.ID)) ON (t5.ID = t8.CUSTOMERUSER_ID) LEFT OUTER JOIN DIRECTORYNUMBER
t4 ON (t4.CUSTOMERUSERROOT_ID = t5.ID), CUSTOMERGROUP t10, ROOTENTITY t9, conf_device t3, CUSTOMERGROUPACCESSDEVICE t1, ROOTENTITY t0 WHERE (((((((t
3.DEVICE_CATEGORY = ?) AND (t3.SOFT_CLIENT = ?)) AND (t10.ccgroupid = ?)) AND (((t6.CCUSERID IS NULL) OR ((t6.CCUSERID <> ?) AND (t8.LOGICALPORTNUM
= ?))) OR (t6.CCUSERID = ?))) AND t2.ID NOT IN (SELECT DISTINCT t11.ID FROM endpoint t11, CUSTOMERUSER t19, CUSTOMERUSERROOT t18, ROOTENTITY t17, EN
DPOINTADDRESS t16, CUSTOMERGROUP t15, ROOTENTITY t14, CUSTOMERGROUPACCESSDEVICE t13, ROOTENTITY t12 WHERE (((t15.ccgroupid = ?) AND (t18.CCUSERID =
?)) AND ((((((t12.ID = t11.CUSTOMERGROUPACCESSDEVICE_ID) AND ((t13.ID = t12.ID) AND (t12.DTYPE = ?))) AND ((t14.ID = t13.CUSTOMERGROUP_ID) AND ((t15
.ID = t14.ID) AND (t14.DTYPE = ?)))) AND (t16.ENDPOINT_ID = t11.ID)) AND (t16.DTYPE = ?)) AND ((t17.ID = t16.CUSTOMERUSER_ID) AND (((t19.ID = t17.ID
) AND ((t18.ID = t17.ID) AND (t18.ID = t17.ID))) AND (t17.DTYPE = ?))))))) AND t2.ID NOT IN (SELECT DISTINCT t20.ID FROM ENDPOINTADDRESS t26 LEFT OU
TER JOIN (ROOTENTITY t27 JOIN CUSTOMERUSERROOT t28 ON (t28.ID = t27.ID) JOIN CUSTOMERUSER t29 ON (t29.ID = t27.ID)) ON (t27.ID = t26.CUSTOMERUSER_ID
), conf_device t25, CUSTOMERGROUP t24, ROOTENTITY t23, CUSTOMERGROUPACCESSDEVICE t22, ROOTENTITY t21, endpoint t20 WHERE ((((t28.CCUSERID <> ?) AND
(t24.ccgroupid = ?)) AND (t25.SOFT_CLIENT = ?)) AND ((((t26.ENDPOINT_ID = t20.ID) AND ((t21.ID = t20.CUSTOMERGROUPACCESSDEVICE_ID) AND ((t22.ID = t2
1.ID) AND (t21.DTYPE = ?)))) AND ((t23.ID = t22.CUSTOMERGROUP_ID) AND ((t24.ID = t23.ID) AND (t23.DTYPE = ?)))) AND (t25.DEVICE_MODEL = t22.DEVICECO
NF_DEVICE_MODEL))) GROUP BY t20.ID, t25.MAX_PORTS_NUM HAVING (t25.MAX_PORTS_NUM <= SUM(t26.lineweight)))) AND ((((t0.ID = t2.CUSTOMERGROUPACCESSDEVI
CE_ID) AND ((t1.ID = t0.ID) AND (t0.DTYPE = ?))) AND (t3.DEVICE_MODEL = t1.DEVICECONF_DEVICE_MODEL)) AND ((t9.ID = t1.CUSTOMERGROUP_ID) AND ((t10.ID
 = t9.ID) AND (t9.DTYPE = ?)))))