<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>com.learn</groupId>

   <artifactId>WebServiceLib</artifactId>

   <version>1.0</version>

   <parent>
      <groupId>com.learn</groupId>

      <artifactId>EJB3JBoss-Basic</artifactId>

      <version>1.0</version>
   </parent>

   <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.build.timestamp.format>yyyy-MM-dd'T'HH:mm:ss</maven.build.timestamp.format>
    <maven.test.skip>false</maven.test.skip>
    <maven.javadoc.skip>true</maven.javadoc.skip>
    <java.version>21</java.version>
    <maven.compiler.release>${java.version}</maven.compiler.release><!-- Java 9 and Beyond -->
    <maven.compiler.target>${java.version}</maven.compiler.target>
    <maven.compiler.source>${java.version}</maven.compiler.source>
    <!-- Other than boot -->
  </properties>

   <dependencies>
      <dependency>
         <groupId>com.sun.xml.ws</groupId>

         <artifactId>jaxws-rt</artifactId>

         <version>2.1.4</version>
      </dependency>
   </dependencies>

   <build>
      <plugins>
         <plugin>
            <artifactId>maven-compiler-plugin</artifactId>
         </plugin>

         <plugin>
            <groupId>org.codehaus.mojo</groupId>

            <artifactId>jaxws-maven-plugin</artifactId>

            <executions>
               <execution>
                  <id>ws1</id>

                  <goals>
                     <goal>wsimport</goal>
                  </goals>

                  <configuration>
                     <wsdlUrls>
                        <wsdlUrl>http://localhost:9080/EJB3JBoss-packaging-EJB3JBoss-ejbs-1.0/MyWebServiceBean?wsdl</wsdlUrl>
                     </wsdlUrls>

                     <packageName>com.learn.webservice</packageName>
                  </configuration>
               </execution>
            </executions>
         </plugin>

         <plugin>
            <groupId>org.apache.maven.plugins</groupId>

            <artifactId>maven-javadoc-plugin</artifactId>

            <executions>
               <execution>
                  <phase>install</phase>

                  <goals>
                     <goal>javadoc</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
      </plugins>
   </build>

   <reporting>
      <plugins>
         <plugin>
            <groupId>org.apache.maven.plugins</groupId>

            <artifactId>maven-javadoc-plugin</artifactId>

            <reportSets>
               <reportSet>
                  <id>html</id>

                  <configuration>
                     <show>private</show>
                  </configuration>

                  <reports>
                     <report>javadoc</report>
                  </reports>
               </reportSet>
            </reportSets>
         </plugin>
      </plugins>
   </reporting>
</project>
