SELECT
    *
FROM
    PARADATA_EVENT
WHERE
    EVENT_DTM IS NOT NULL
AND TO_CHAR(EVENT_DTM, 'yyyy-mm-dd') = '2020-11-05' --  TO_CHAR(SYSDATE, 'yyyy-mm-dd')
ORDER BY
    EVENT_DTM DESC
FETCH
    FIRST 100 rows only