SELECT
    s.SURVEY_ID,
    s.DISPLAY_NAME,
    st.DESCR,
    st.ODSY_SURVEY_FLG,
    si.SURVEY_INSTANCE_ID,
    si.SMART_ID,
    su.USER_ACCOUNT_ID,
    sit.STATUS_INDICATOR_NAME,
    ua.FIRST_NAME,
    ua.LAST_NAME,
    ua.EMAIL
FROM
    SURVEY                s,
    SURVEY_SCHEDULE       ss,
    SURVEY_INSTANCE       si,
    SURVEY_USER           su,
    USER_ACCOUNT          ua,
    SURVEY_TYPE           st,
    STATUS_INDICATOR_TYPE sit
WHERE
    s.SURVEY_ID = ss.SURVEY_ID
AND s.SURVEY_ID = si.SURVEY_ID
AND su.SURVEY_INSTANCE_ID = si.SURVEY_INSTANCE_ID
AND st.SURVEY_TYPE_ID = s.SURVEY_TYPE_ID
AND su.USER_ACCOUNT_ID = ua.USER_ACCOUNT_ID
AND sit.STATUS_INDICATOR_ID = si.STATUS_INDICATOR
AND lower(ua.LAST_NAME) LIKE 'ma'
AND lower(ua.EMAIL) LIKE 'lukemal@%';