<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
   <parent>
      <groupId>com.learn</groupId>

      <artifactId>ParentChild</artifactId>

      <version>1.0</version>
   </parent>

   <modelVersion>4.0.0</modelVersion>

   <groupId>com.learn</groupId>

   <artifactId>Bidirectional-JoinTable</artifactId>

   <version>1.0</version>

   <packaging>pom</packaging>

   <modules>
      <module>Bidirectional-JoinTable-OneToMany-ManyToOne-yes</module>

      <module>Bidirectional-JoinTable-OneToOne-rare</module>

      <module>Bidirectional-JoinTable-ManyToMany-yes</module>
   </modules>
</project>
