insert into country (id, code, name) values (1, 'US', 'United States');
insert into country (id, code, name) values (2, 'CA', 'Canada');
insert into country (id, code, name) values (3, 'GB', 'United Kingdom');
insert into country (id, code, name) values (4, 'AF', 'Afghanistan');
insert into country (id, code, name) values (5, 'AL', 'Albania');
insert into country (id, code, name) values (6, 'DZ', 'Algeria');
insert into country (id, code, name) values (7, 'AS', 'American Samoa');
insert into country (id, code, name) values (8, 'AD', 'Andorra');
insert into country (id, code, name) values (9, 'AO', 'Angola');
insert into country (id, code, name) values (10, 'AI', 'Anguilla');
insert into country (id, code, name) values (11, 'AG', 'Antigua and Barbuda');
insert into country (id, code, name) values (12, 'AR', 'Argentina');
insert into country (id, code, name) values (13, 'AM', 'Armenia');
insert into country (id, code, name) values (14, 'AW', 'Aruba');
insert into country (id, code, name) values (15, 'AU', 'Australia');
insert into country (id, code, name) values (16, 'AT', 'Austria');
insert into country (id, code, name) values (17, 'AZ', 'Azerbaijan Republic');
insert into country (id, code, name) values (18, 'BS', 'Bahamas');
insert into country (id, code, name) values (19, 'BH', 'Bahrain');
insert into country (id, code, name) values (20, 'BD', 'Bangladesh');
insert into country (id, code, name) values (21, 'BB', 'Barbados');
insert into country (id, code, name) values (22, 'BY', 'Belarus');
insert into country (id, code, name) values (23, 'BE', 'Belgium');
insert into country (id, code, name) values (24, 'BZ', 'Belize');
insert into country (id, code, name) values (25, 'BJ', 'Benin');
insert into country (id, code, name) values (26, 'BM', 'Bermuda');
insert into country (id, code, name) values (27, 'BT', 'Bhutan');
insert into country (id, code, name) values (28, 'BO', 'Bolivia');
insert into country (id, code, name) values (29, 'BA', 'Bosnia and Herzegovina');
insert into country (id, code, name) values (30, 'BW', 'Botswana');
insert into country (id, code, name) values (31, 'BR', 'Brazil');
insert into country (id, code, name) values (32, 'IO', 'British Virgin Islands');
insert into country (id, code, name) values (33, 'BN', 'Brunei Darussalam');
insert into country (id, code, name) values (34, 'BG', 'Bulgaria');
insert into country (id, code, name) values (35, 'BF', 'Burkina Faso');
insert into country (id, code, name) values (36, 'BI', 'Burundi');
insert into country (id, code, name) values (37, 'KH', 'Cambodia');
insert into country (id, code, name) values (38, 'CM', 'Cameroon');
insert into country (id, code, name) values (39, 'CA', 'Canada');
insert into country (id, code, name) values (40, 'CV', 'Cape Verde Islands');
insert into country (id, code, name) values (41, 'KY', 'Cayman Islands');
insert into country (id, code, name) values (42, 'CF', 'Central African Republic');
insert into country (id, code, name) values (43, 'TD', 'Chad');
insert into country (id, code, name) values (44, 'CL', 'Chile');
insert into country (id, code, name) values (45, 'CN', 'China Mainland');
insert into country (id, code, name) values (46, 'CO', 'Colombia');
insert into country (id, code, name) values (47, 'KM', 'Comoros');
insert into country (id, code, name) values (48, 'CD', 'Congo');
insert into country (id, code, name) values (49, 'CG', 'Congo');
insert into country (id, code, name) values (50, 'CK', 'Cook Islands');
insert into country (id, code, name) values (51, 'CR', 'Costa Rica');
insert into country (id, code, name) values (52, 'CI', 'Cote d Ivoire (Ivory Coast)');
insert into country (id, code, name) values (53, 'HR', 'Croatia');
insert into country (id, code, name) values (54, 'CW', 'Curacao');
insert into country (id, code, name) values (55, 'CY', 'Cyprus');
insert into country (id, code, name) values (56, 'CZ', 'Czech Republic');
insert into country (id, code, name) values (57, 'DK', 'Denmark');
insert into country (id, code, name) values (58, 'DJ', 'Djibouti');
insert into country (id, code, name) values (59, 'DM', 'Dominica');
insert into country (id, code, name) values (60, 'DO', 'Dominican Republic');
insert into country (id, code, name) values (61, 'EC', 'Ecuador');
insert into country (id, code, name) values (62, 'EG', 'Egypt');
insert into country (id, code, name) values (63, 'SV', 'El Salvador');
insert into country (id, code, name) values (64, 'GQ', 'Equatorial Guinea');
insert into country (id, code, name) values (65, 'ER', 'Eritrea');
insert into country (id, code, name) values (66, 'EE', 'Estonia');
insert into country (id, code, name) values (67, 'ET', 'Ethiopia');
insert into country (id, code, name) values (68, 'FK', 'Falkland Islands (Islas Malvinas)');
insert into country (id, code, name) values (69, 'FJ', 'Fiji');
insert into country (id, code, name) values (70, 'FI', 'Finland');
insert into country (id, code, name) values (71, 'FR', 'France');
insert into country (id, code, name) values (72, 'GF', 'French Guiana');
insert into country (id, code, name) values (73, 'FP', 'French Polynesia');
insert into country (id, code, name) values (74, 'GA', 'Gabon Republic');
insert into country (id, code, name) values (75, 'GM', 'Gambia');
insert into country (id, code, name) values (76, 'GE', 'Georgia');
insert into country (id, code, name) values (77, 'DE', 'Germany');
insert into country (id, code, name) values (78, 'GH', 'Ghana');
insert into country (id, code, name) values (79, 'GI', 'Gibraltar');
insert into country (id, code, name) values (80, 'GR', 'Greece');
insert into country (id, code, name) values (81, 'GL', 'Greenland');
insert into country (id, code, name) values (82, 'GD', 'Grenada');
insert into country (id, code, name) values (83, 'GP', 'Guadeloupe');
insert into country (id, code, name) values (84, 'GU', 'Guam');
insert into country (id, code, name) values (85, 'GT', 'Guatemala');
insert into country (id, code, name) values (86, 'GG', 'Guernsey');
insert into country (id, code, name) values (87, 'GN', 'Guinea');
insert into country (id, code, name) values (88, 'GW', 'Guinea-Bissau');
insert into country (id, code, name) values (89, 'GY', 'Guyana');
insert into country (id, code, name) values (90, 'HT', 'Haiti');
insert into country (id, code, name) values (91, 'HN', 'Honduras');
insert into country (id, code, name) values (92, 'HK', 'Hong Kong');
insert into country (id, code, name) values (93, 'HU', 'Hungary');
insert into country (id, code, name) values (94, 'IS', 'Iceland');
insert into country (id, code, name) values (95, 'IN', 'India');
insert into country (id, code, name) values (96, 'ID', 'Indonesia');
insert into country (id, code, name) values (97, 'IE', 'Ireland');
insert into country (id, code, name) values (98, 'IL', 'Israel');
insert into country (id, code, name) values (99, 'IT', 'Italy');
insert into country (id, code, name) values (100, 'JM', 'Jamaica');
insert into country (id, code, name) values (101, 'JN', 'Jan Mayen');
insert into country (id, code, name) values (102, 'JP', 'Japan');
insert into country (id, code, name) values (103, 'JE', 'Jersey');
insert into country (id, code, name) values (104, 'JO', 'Jordan');
insert into country (id, code, name) values (105, 'KZ', 'Kazakhstan');
insert into country (id, code, name) values (106, 'KE', 'Kenya');
insert into country (id, code, name) values (107, 'KI', 'Kiribati');
insert into country (id, code, name) values (108, 'KR', 'Korea');
insert into country (id, code, name) values (109, 'KW', 'Kuwait');
insert into country (id, code, name) values (110, 'KG', 'Kyrgyzstan');
insert into country (id, code, name) values (111, 'LA', 'Laos');
insert into country (id, code, name) values (112, 'LV', 'Latvia');
insert into country (id, code, name) values (113, 'LB', 'Lebanon');
insert into country (id, code, name) values (114, 'LI', 'Liechtenstein');
insert into country (id, code, name) values (115, 'LT', 'Lithuania');
insert into country (id, code, name) values (116, 'LU', 'Luxembourg');
insert into country (id, code, name) values (117, 'MO', 'Macau');
insert into country (id, code, name) values (118, 'MK', 'Macedonia');
insert into country (id, code, name) values (119, 'MG', 'Madagascar');
insert into country (id, code, name) values (120, 'MW', 'Malawi');
insert into country (id, code, name) values (121, 'MY', 'Malaysia');
insert into country (id, code, name) values (122, 'MV', 'Maldives');
insert into country (id, code, name) values (123, 'ML', 'Mali');
insert into country (id, code, name) values (124, 'MT', 'Malta');
insert into country (id, code, name) values (125, 'MH', 'Marshall Islands');
insert into country (id, code, name) values (126, 'MQ', 'Martinique');
insert into country (id, code, name) values (127, 'MR', 'Mauritania');
insert into country (id, code, name) values (128, 'MU', 'Mauritius');
insert into country (id, code, name) values (129, 'YT', 'Mayotte');
insert into country (id, code, name) values (130, 'MX', 'Mexico');
insert into country (id, code, name) values (131, 'FM', 'Micronesia');
insert into country (id, code, name) values (132, 'MD', 'Moldova');
insert into country (id, code, name) values (133, 'MC', 'Monaco');
insert into country (id, code, name) values (134, 'MN', 'Mongolia');
insert into country (id, code, name) values (135, 'ME', 'Montenegro');
insert into country (id, code, name) values (136, 'MS', 'Montserrat');
insert into country (id, code, name) values (137, 'MA', 'Morocco');
insert into country (id, code, name) values (138, 'MZ', 'Mozambique');
insert into country (id, code, name) values (139, 'NA', 'Namibia');
insert into country (id, code, name) values (140, 'NR', 'Nauru');
insert into country (id, code, name) values (141, 'NP', 'Nepal');
insert into country (id, code, name) values (142, 'NL', 'Netherlands');
insert into country (id, code, name) values (143, 'AN', 'Netherlands Antilles');
insert into country (id, code, name) values (144, 'NC', 'New Caledonia');
insert into country (id, code, name) values (145, 'NZ', 'New Zealand');
insert into country (id, code, name) values (146, 'NI', 'Nicaragua');
insert into country (id, code, name) values (147, 'NE', 'Niger');
insert into country (id, code, name) values (148, 'NG', 'Nigeria');
insert into country (id, code, name) values (149, 'NU', 'Niue');
insert into country (id, code, name) values (150, 'NO', 'Norway');
insert into country (id, code, name) values (151, 'OM', 'Oman');
insert into country (id, code, name) values (152, 'PK', 'Pakistan');
insert into country (id, code, name) values (153, 'PW', 'Palau');
insert into country (id, code, name) values (154, 'PA', 'Panama');
insert into country (id, code, name) values (155, 'PG', 'Papua New Guinea');
insert into country (id, code, name) values (156, 'PY', 'Paraguay');
insert into country (id, code, name) values (157, 'PE', 'Peru');
insert into country (id, code, name) values (158, 'PH', 'Philippines');
insert into country (id, code, name) values (159, 'PL', 'Poland');
insert into country (id, code, name) values (160, 'PT', 'Portugal');
insert into country (id, code, name) values (161, 'PR', 'Puerto Rico');
insert into country (id, code, name) values (162, 'QA', 'Qatar');
insert into country (id, code, name) values (163, 'RE', 'Reunion');
insert into country (id, code, name) values (164, 'RO', 'Romania');
insert into country (id, code, name) values (165, 'RU', 'Russian Federation');
insert into country (id, code, name) values (166, 'RW', 'Rwanda');
insert into country (id, code, name) values (167, 'SH', 'Saint Helena');
insert into country (id, code, name) values (168, 'KN', 'Saint Kitts-Nevis');
insert into country (id, code, name) values (169, 'LC', 'Saint Lucia');
insert into country (id, code, name) values (170, 'PM', 'Saint Pierre and Miquelon');
insert into country (id, code, name) values (171, 'VC', 'Saint Vincent and the Grenadines');
insert into country (id, code, name) values (172, 'SM', 'San Marino');
insert into country (id, code, name) values (173, 'SA', 'Saudi Arabia');
insert into country (id, code, name) values (174, 'SN', 'Senegal');
insert into country (id, code, name) values (175, 'RS', 'Serbia');
insert into country (id, code, name) values (176, 'SC', 'Seychelles');
insert into country (id, code, name) values (177, 'SL', 'Sierra Leone');
insert into country (id, code, name) values (178, 'SG', 'Singapore');
insert into country (id, code, name) values (179, 'SK', 'Slovakia');
insert into country (id, code, name) values (180, 'SI', 'Slovenia');
insert into country (id, code, name) values (181, 'SB', 'Solomon Islands');
insert into country (id, code, name) values (182, 'SO', 'Somalia');
insert into country (id, code, name) values (183, 'ZA', 'South Africa');
insert into country (id, code, name) values (184, 'ES', 'Spain');
insert into country (id, code, name) values (185, 'LK', 'Sri Lanka');
insert into country (id, code, name) values (186, 'SR', 'Suriname');
insert into country (id, code, name) values (187, 'SJ', 'Svalbard');
insert into country (id, code, name) values (188, 'SZ', 'Swaziland');
insert into country (id, code, name) values (189, 'SE', 'Sweden');
insert into country (id, code, name) values (190, 'CH', 'Switzerland');
insert into country (id, code, name) values (191, 'TA', 'Tahiti');
insert into country (id, code, name) values (192, 'TW', 'Taiwan');
insert into country (id, code, name) values (193, 'TJ', 'Tajikistan');
insert into country (id, code, name) values (194, 'TZ', 'Tanzania');
insert into country (id, code, name) values (195, 'TH', 'Thailand');
insert into country (id, code, name) values (196, 'TG', 'Togo');
insert into country (id, code, name) values (197, 'TO', 'Tonga');
insert into country (id, code, name) values (198, 'TT', 'Trinidad and Tobago');
insert into country (id, code, name) values (199, 'TN', 'Tunisia');
insert into country (id, code, name) values (200, 'TR', 'Turkey');
insert into country (id, code, name) values (201, 'TM', 'Turkmenistan');
insert into country (id, code, name) values (202, 'TC', 'Turks and Caicos Islands');
insert into country (id, code, name) values (203, 'TV', 'Tuvalu');
insert into country (id, code, name) values (204, 'UG', 'Uganda');
insert into country (id, code, name) values (205, 'UA', 'Ukraine');
insert into country (id, code, name) values (206, 'AE', 'United Arab Emirates');
insert into country (id, code, name) values (207, 'GB', 'United Kingdom');
insert into country (id, code, name) values (208, 'US', 'United States');
insert into country (id, code, name) values (209, 'UY', 'Uruguay');
insert into country (id, code, name) values (210, 'UZ', 'Uzbekistan');
insert into country (id, code, name) values (211, 'VU', 'Vanuatu');
insert into country (id, code, name) values (212, 'VA', 'Vatican City State');
insert into country (id, code, name) values (213, 'VE', 'Venezuela');
insert into country (id, code, name) values (214, 'VN', 'Vietnam');
insert into country (id, code, name) values (215, 'VI', 'Virgin Islands (U.S.)');
insert into country (id, code, name) values (216, 'WF', 'Wallis and Futuna');
insert into country (id, code, name) values (217, 'EH', 'Western Sahara');
insert into country (id, code, name) values (218, 'WS', 'Western Samoa');
insert into country (id, code, name) values (219, 'YE', 'Yemen');
insert into country (id, code, name) values (220, 'ZM', 'Zambia');
insert into country (id, code, name) values (221, 'ZW', 'Zimbabwe');
