
logfile-name-prefix=log4j2-ec2-docker

welcome.message=Hello Mkyong on ec2
Access-Control-Allow-Origin=http://ec2-54-198-112-75.compute-1.amazonaws.com

server.servlet.context-path=/my-properties-boot



