
logfile-name-prefix=log4j2

welcome.message=Hello Mkyong on laptop
# Access-Control-Allow-Origin=http://localhost:4200
Access-Control-Allow-Origin=*

server.servlet.context-path=/my-properties-boot




