<?xml version="1.0" encoding="ISO-8859-1" ?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
   <xsd:element name="PNRRemark">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="pnr" type="PNRType" />

            <xsd:element name="remark" type="RemarkType" minOccurs="0" maxOccurs="unbounded" />
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:simpleType name="PNRType">
      <xsd:restriction base="xsd:string">
         <xsd:pattern value="[a-zA-Z0-9]{6}" />
      </xsd:restriction>
   </xsd:simpleType>

   <xsd:simpleType name="RemarkType">
      <xsd:restriction base="xsd:string">
         <xsd:whiteSpace value="collapse" />
      </xsd:restriction>
   </xsd:simpleType>
</xsd:schema>

