package com.learn.cucumber.test;


import org.junit.Assert;

import com.learn.cucumber.HelloCucumber;
import com.learn.cucumber.Situation;

import io.cucumber.java.en.Given;
import io.cucumber.java.en.Then;
import io.cucumber.java.en.When;
import lombok.extern.log4j.Log4j2;


@Log4j2
//@formatter:off
/**
* When no feature path is provided, Cucumber will use the package of theannotated class. For example, if the annotated
* class is com.example.RunCucumber then features are assumed to be locatedin classpath:com/example.
*/
/*
@CucumberOptions(monochrome = true,
              // glue = {"com.learn.cucumber.test.StepDefinitions"},
              stepNotifications = true,
              plugin = { "pretty",
                         // html report generated by maven-cucumber-reporting looks better.
                         // "html:target/cucumber-html-report-friday.htm",
                         "json:target/json-reports/hello-cucumber.json"
                       })
                       */
//@formatter:on
public class HelloCucumberSteps {

    HelloCucumber helloCucumber = new HelloCucumber();
    Situation situation;
    String status;

    /**
     * Scenario: Hello Cucumer Simple Scenario
     */
    @Given("I want to write a step with precondition")
    public void i_want_to_write_a_step_with_precondition() {
        log.debug(() -> "Given I want to write a step with precondition");
    }

    @Given("some other precondition")
    public void some_other_precondition() {
        log.debug(() -> "Given some other precondition");
    }

    @When("I complete action")
    public void i_complete_action() {
        log.debug(() -> "When I complete action");
    }

    @When("some other action")
    public void some_other_action() {
        log.debug(() -> "When some other action");
    }

    @When("yet another action")
    public void yet_another_action() {
        log.debug(() -> "When yet another action");
    }

    @Then("I validate the outcomes")
    public void i_validate_the_outcomes() {
        log.debug(() -> "Then I validate the outcomes");
    }

    @Then("check more outcomes")
    public void check_more_outcomes() {
        log.debug(() -> "Then check more outcomes");
    }

    /**
     * Scenario Outline: Hello Cucumber Scenario Outline
     */
    @Given("I want to write a step with {string}")
    public void i_want_to_write_a_step_with(String name) {
        log.debug("I want to write a step with {}", () -> name);
        this.situation = this.helloCucumber.getSituationByName(name);
    }

    @When("I check for the {int} in step")
    public void i_check_for_the_in_step(Integer value) {
        log.debug("I check for the {} in step", () -> value);
        if (this.situation.getValue() == value) {
            this.status = this.situation.getStatus();
        }
    }

    @Then("I verify the {string} in step")
    public void i_verify_the_in_step(String status) {
        log.debug("I verify the {} in step", () -> status);
        Assert.assertEquals("statu", status, this.status);
    }

}
