package com.learn.cucumber.test;


import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;

/**
 * cucumber junit integration:
 * 
 * https://cucumber.io/docs/cucumber/api/#junit
 * 
 * Cucumber is based on JUnit 4. If you’re using JUnit 5, remember to include junit-vintage-engine dependency, as well.
 * 
 * 1. This will execute all scenarios in same package as the runner.
 * 2. By default glue code is also assumed to be in the same package.
 */
// @formatter:off
@RunWith(Cucumber.class)
/**
 * When no feature path is provided, Cucumber will use the package of theannotated class. For example, if the annotated
 * class is com.example.RunCucumber then features are assumed to be locatedin classpath:com/example.
 */
@CucumberOptions(// monochrome = true,
                 /**
                  * glue is a list of Step definition classes or Step package names
                  */
                 // glue = {"com.learn.cucumber.test.StepDefinitions", "com.learn.cucumber.test.HelloCucumberSteps"},
                 // glue = {"com.learn.cucumber.test", "com.learn.selenium.test"},
                 // stepNotifications = true,
                 /**
                  * features are a list of feature files or feature file folders.
                  */
                 /*
                 features = { "src/it/resources/com/learn/cucumber/test/hello-cucumber.feature",
                              // "src/it/resources/com/learn/selenium/test"
                            },
                 */
                 plugin = { // "pretty",
                            // html report generated by maven-cucumber-reporting looks better.
                            // "html:target/cucumber-html-report-friday.htm",
                            "json:target/json-reports/cucumber-json-report-friday.json"
                          })
// @formatter:on
public class RunCucumberTest {

}
