<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>JMock</artifactId>

	<packaging>jar</packaging>

	<name>${project.artifactId}</name>

	<parent>
		<groupId>com.learn</groupId>

		<artifactId>Parent</artifactId>

		<version>1.0</version>

		<relativePath>../Parent</relativePath>
	</parent>

	<dependencies>
		<dependency>
			<groupId>log4j</groupId>

			<artifactId>log4j</artifactId>
		</dependency>

		<dependency>
			<groupId>junit</groupId>

			<artifactId>junit</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jmock</groupId>

			<artifactId>jmock</artifactId>
		</dependency>

		<dependency>
			<groupId>org.jmock</groupId>

			<artifactId>jmock-junit4</artifactId>
		</dependency>
	</dependencies>

</project>
