
CREATE SCHEMA BMS AUTHORIZATION SA;

-- ALTER USER SA SET INITIAL SCHEMA BMS;

SELECT * FROM INFORMATION_SCHEMA.SYSTEM_USERS;
SELECT * FROM INFORMATION_SCHEMA.SYSTEM_SCHEMAS;
SELECT * FROM INFORMATION_SCHEMA.SYSTEM_TABLES;
SELECT * FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES;
SELECT * FROM INFORMATION_SCHEMA.TABLES;
