SELECT ID_PART_CPRT,
  STREET_ADR_ID_CPRT,
  NME_PART_CPRT,
  NO_FAX_CONTACT_CPRT,
  CDE_EMAIL_ADDRESS_CPRT
FROM CASEPART
WHERE NME_PART_CPRT LIKE 'BOEING COMP%'
ORDER BY 1,
  2;
--
--
SELECT PARTICIPANT.ISN,
  ID_PART,
  NME_PART,
  ADDR_CITY_PART
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART =332308)
ORDER BY (0+ISN);
--
--
SELECT PARTICIPANT.ISN,
  ID_PART,
  NME_PART,
  ADDR_CITY_PART
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART =369195)
ORDER BY (0+ISN);
--
--
SELECT FINANCE.ISN,
  ID_UNIQUE_FIN,
  OPTION_FIN,
  COMP_FIN,
  AMT_US_FIN,
  AMT_EF_FIN,
  AMT_CONTRACT_PRICE_FIN
FROM FINANCE
WHERE (FINANCE.ID_UNIQUE_FIN ='0000056798')
ORDER BY (0+ISN);
--
--
SELECT *
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART =369195
AND STREET_ADR_ID          = '298035')
ORDER BY (0+ISN);
--
--
SELECT *
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART =369195
AND STREET_ADR_ID          = '319735')
ORDER BY (0+ISN);
--
--
SELECT PARTICIPANT.ISN,
  ID_PART,
  NME_PART,
  ADDR_CITY_PART,
  STREET_ADR_ID
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART     =599)
AND (PARTICIPANT.STREET_ADR_ID =21772)
ORDER BY (0+ISN);
--
--
SELECT CASEPROD.ISN,
  ID_UNIQUE_CPRD,
  ID_PART_CPRD,
  AMT_PROD_CPRD,
  ID_SUPPLIER_CPRD,
  ID_MANUFACTURER_CPRD,
  AMT_FORGN_CONTENT_CPRD,
  NUM_SUPPLY_CONTRACT_CPRD
FROM CASEPROD
WHERE (CASEPROD.ID_UNIQUE_CPRD >='0000056798')
AND (CASEPROD.ID_UNIQUE_CPRD   <='0000056798')
ORDER BY ID_UNIQUE_CPRD,
  ISN;
--
--
SELECT SUPPLY_CONTRACT.ISN,
  ID_UNIQUE_SCRCT,
  ID_EXPORTER_SCRCT,
  NUM_SUPPLY_CONTRACT_SCRCT,
  AMT_SUPPLY_CONTRACT_SCRCT,
  DTE_SUPPLY_CONTRACT_SCRCT,
  DTE_EXPRT_CERT_RECVD_SCRCT,
  PCT_DISB_SCRCT,
  DTE_CONTRACT_RPT_RECVD_SCRCT
FROM SUPPLY_CONTRACT
WHERE (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT IS NOT NULL
AND SUPPLY_CONTRACT.ID_UNIQUE_SCRCT    >='0000056798')
AND (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT   <='0000056798')
ORDER BY ID_UNIQUE_SCRCT,
  ISN;
--
--
SELECT FINANCE.ISN,
  ID_UNIQUE_FIN,
  OPTION_FIN,
  COMP_FIN,
  AMT_US_FIN,
  AMT_EF_FIN,
  AMT_CONTRACT_PRICE_FIN
FROM FINANCE
WHERE (FINANCE.ID_UNIQUE_FIN ='0000056798')
ORDER BY (0+ISN);
--
--
SELECT CASEPART.ISN,
  ID_UNIQUE_CPRT,
  ID_PART_CPRT,
  STREET_ADR_ID_CPRT
FROM CASEPART
WHERE (CASEPART.SPD_UNIQ_PART_CP >=hextoraw('F0F0F0F0F0F5F6F7F9F8404040404040404040'))
ORDER BY SPD_UNIQ_PART_CP,
  ISN;
--
--
SELECT * FROM casepart WHERE ID_UNIQUE_CPRT LIKE '%83800';
--
--
SELECT * FROM casepart_mu WHERE isn IN (378338,378339, 378345);
--
--
SELECT EXP_STR_ADR_ID_SCRCT,
  s.*
FROM SUPPLY_CONTRACT s
WHERE ID_UNIQUE_SCRCT LIKE '%83800';
--
SELECT * FROM caseprod WHERE ID_UNIQUE_CPRD LIKE '%83800';
--
SELECT *
FROM case_field
WHERE ID_CASE = 'AP088857XX'
AND ID_SUBTYPE_CASE LIKE 'A%';
--
SELECT *
FROM participant
WHERE id_part     = '144307'
AND STREET_ADR_ID = '482307';
--
SELECT SUPPLY_CONTRACT.ISN,
  ID_UNIQUE_SCRCT,
  ID_EXPORTER_SCRCT,
  NUM_SUPPLY_CONTRACT_SCRCT,
  AMT_SUPPLY_CONTRACT_SCRCT,
  DTE_SUPPLY_CONTRACT_SCRCT,
  DTE_EXPRT_CERT_RECVD_SCRCT,
  PCT_DISB_SCRCT,
  DTE_CONTRACT_RPT_RECVD_SCRCT,
  EXP_STR_ADR_ID_SCRCT
FROM SUPPLY_CONTRACT
WHERE (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT   IS NOT NULL
AND SUPPLY_CONTRACT.ID_UNIQUE_SCRCT      >='0000083800')
AND (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT     <='0000083800')
AND (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT = '297836')
ORDER BY ID_UNIQUE_SCRCT,
  ISN;
--
--
SELECT *
FROM
  (SELECT SUPPLY_CONTRACT.ISN,
    ID_UNIQUE_SCRCT,
    ID_EXPORTER_SCRCT,
    NUM_SUPPLY_CONTRACT_SCRCT,
    AMT_SUPPLY_CONTRACT_SCRCT,
    DTE_SUPPLY_CONTRACT_SCRCT,
    DTE_EXPRT_CERT_RECVD_SCRCT,
    PCT_DISB_SCRCT,
    DTE_CONTRACT_RPT_RECVD_SCRCT,
    EXP_STR_ADR_ID_SCRCT
  FROM SUPPLY_CONTRACT
  WHERE (SUPPLY_CONTRACT.SPD_UNIQ_XPRT_SPPLY_SCRCT IS NOT NULL)
  AND SUPPLY_CONTRACT.SPD_UNIQ_XPRT_SPPLY_SCRCT    >=hextoraw('F0F0F0F0F0F8F3F8F0F5F3F6F9F1F9F540404040404040404040404040')
  )
AND (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT                 ='298035')
ORDER BY SPD_UNIQ_XPRT_SPPLY_SCRCT ) tquery WHERE rownum <= 13;
--
SELECT *
FROM
  (SELECT SUPPLY_CONTRACT.ISN,
    ID_UNIQUE_SCRCT,
    ID_EXPORTER_SCRCT,
    NUM_SUPPLY_CONTRACT_SCRCT,
    AMT_SUPPLY_CONTRACT_SCRCT,
    DTE_SUPPLY_CONTRACT_SCRCT,
    DTE_EXPRT_CERT_RECVD_SCRCT,
    PCT_DISB_SCRCT,
    DTE_CONTRACT_RPT_RECVD_SCRCT,
    EXP_STR_ADR_ID_SCRCT
  FROM SUPPLY_CONTRACT
  WHERE (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT ='298035')
  ORDER BY SPD_UNIQ_XPRT_SPPLY_SCRCT
  ) tquery
WHERE rownum <= 13;
--
SELECT SUPPLY_CONTRACT.ISN,
  ID_UNIQUE_SCRCT,
  ID_EXPORTER_SCRCT,
  NUM_SUPPLY_CONTRACT_SCRCT,
  AMT_SUPPLY_CONTRACT_SCRCT,
  DTE_SUPPLY_CONTRACT_SCRCT,
  DTE_EXPRT_CERT_RECVD_SCRCT,
  PCT_DISB_SCRCT,
  DTE_CONTRACT_RPT_RECVD_SCRCT,
  EXP_STR_ADR_ID_SCRCT
FROM SUPPLY_CONTRACT
WHERE (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT ='298035')
ORDER BY (0+ISN);
--
SELECT *
FROM
  (SELECT SUPPLY_CONTRACT.ISN,
    ID_UNIQUE_SCRCT,
    ID_EXPORTER_SCRCT,
    NUM_SUPPLY_CONTRACT_SCRCT,
    AMT_SUPPLY_CONTRACT_SCRCT,
    DTE_SUPPLY_CONTRACT_SCRCT,
    DTE_EXPRT_CERT_RECVD_SCRCT,
    PCT_DISB_SCRCT,
    DTE_CONTRACT_RPT_RECVD_SCRCT,
    EXP_STR_ADR_ID_SCRCT
  FROM SUPPLY_CONTRACT
  WHERE (SUPPLY_CONTRACT.SPD_UNIQ_XPRT_SPPLY_SCRCT IS NOT NULL
  AND SUPPLY_CONTRACT.SPD_UNIQ_XPRT_SPPLY_SCRCT    >=hextoraw('F0F0F0F0F0F8F3F8F0F5F3F6F9F1F9F540404040404040404040404040'))
  AND (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT         ='298035')
  ORDER BY SPD_UNIQ_XPRT_SPPLY_SCRCT
  ) tquery
WHERE rownum <= 13;
--
--
/*
BEGIN
INSERT
INTO SUPPLY_CONTRACT
(
ISN,
ID_UNIQUE_SCRCT,
ID_EXPORTER_SCRCT,
NUM_SUPPLY_CONTRACT_SCRCT,
AMT_SUPPLY_CONTRACT_SCRCT,
DTE_SUPPLY_CONTRACT_SCRCT,
DTE_EXPRT_CERT_RECVD_SCRCT,
PCT_DISB_SCRCT,
DTE_CONTRACT_RPT_RECVD_SCRCT
)
VALUES
(
SUPPLY_CONTRACT_ISN.nextval,
?,
?,
?,
?,
?,
?,
?,
?
)
RETURNING ISN
INTO ?;
END;
--
--
BEGIN
INSERT
INTO CASEPROD
(
ISN,
ID_UNIQUE_CPRD,
ID_PART_CPRD,
NO_PROD_SIC_CPRD,
CDE_NEW_USED_CPRD,
CDE_BEN_ENVIR_CPRD,
AMT_PROD_CPRD,
DESC_PROD_CPRD,
NO_PROD_NAICS_CPRD,
ID_SUPPLIER_CPRD,
ID_MANUFACTURER_CPRD,
AMT_FORGN_CONTENT_CPRD,
CDE_FORGN_CONTENT_CNTRY_CPRD,
NUM_SUPPLY_CONTRACT_CPRD,
DESC_FORGN_CONTENT_CPRD,
PCT_USED_CPRD
)
VALUES
(
CASEPROD_ISN.nextval,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?,
?
)
RETURNING ISN
INTO ?;
END;
*/
--
--
SELECT *
FROM caseprod
WHERE ID_PART_CPRD = '369195'
ORDER BY isn;
--
--
SELECT *
FROM SUPPLY_CONTRACT
WHERE ID_EXPORTER_SCRCT = '369195'
ORDER BY isn;
--
SELECT *
FROM participant
WHERE id_part     = '369195'
AND STREET_ADR_ID = '298035';
SELECT *
FROM CASEPART
WHERE ID_PART_CPRT = '369195'
AND STREET_ADR_ID  = '470350';
--
/*
UPDATE caseprod
SET AMT_PROD_CPRD  = '11'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127583 ;
UPDATE caseprod
SET AMT_PROD_CPRD  = '22'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127579 ;
UPDATE caseprod
SET AMT_PROD_CPRD  = '33'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127580 ;
UPDATE caseprod
SET AMT_PROD_CPRD  = '44'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127599 ;
UPDATE caseprod
SET AMT_PROD_CPRD  = '55'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127592 ;
UPDATE caseprod
SET AMT_PROD_CPRD  = '23456'
WHERE ID_PART_CPRD = '369195'
AND ISN            = 127593 ;
--
UPDATE SUPPLY_CONTRACT
SET AMT_SUPPLY_CONTRACT_SCRCT = '1234'
WHERE ID_EXPORTER_SCRCT       = '369195'
AND isn                       = '37845';
UPDATE SUPPLY_CONTRACT
SET AMT_SUPPLY_CONTRACT_SCRCT = '44'
WHERE ID_EXPORTER_SCRCT       = '369195'
AND isn                       = '37850';
COMMIT;
*/
--
--DELETE FROM caseprod WHERE ID_PART_CPRD = '369195';
--DELETE FROM SUPPLY_CONTRACT WHERE ID_EXPORTER_SCRCT = '369195';
--
--
COMMIT;
--
/*
INSERT
INTO SUPPLY_CONTRACT
(
ISN,
ID_UNIQUE_SCRCT,
ID_EXPORTER_SCRCT,
NUM_SUPPLY_CONTRACT_SCRCT,
AMT_SUPPLY_CONTRACT_SCRCT,
DTE_SUPPLY_CONTRACT_SCRCT,
DTE_EXPRT_CERT_RECVD_SCRCT,
PCT_DISB_SCRCT,
DTE_CONTRACT_RPT_RECVD_SCRCT
)
VALUES
(
SUPPLY_CONTRACT_ISN.nextval, -- ISN
'0000083805',                --1
'369195',                    --2
'ABCEG',                     --3
'000000000000111',           --4
'00000000',                  --5
'00000000',                  --6
'000.00',                    --7
'00000000'                   -- 8
);
*/
--
--
--SELECT STREET_ADR_ID_CPRT
SELECT *
FROM CASEPART
WHERE ID_UNIQUE_CPRT ='0000083805'
AND ID_PART_CPRT     = '369195';
--
/*
SELECT STREET_ADR_ID_CPRT
FROM CASEPART
WHERE ID_UNIQUE_CPRT ='0000083805'
AND ID_PART_CPRT     = '418408';
*/
--
--commit;
--
--
SELECT NVL(NULL, '@#$#')
FROM dual;
--
SELECT CASEPROD.ISN,
  ID_UNIQUE_CPRD,
  ID_PART_CPRD,
  NO_PROD_SIC_CPRD,
  CDE_NEW_USED_CPRD,
  CDE_BEN_ENVIR_CPRD,
  AMT_PROD_CPRD,
  DESC_PROD_CPRD,
  NO_PROD_NAICS_CPRD,
  ID_SUPPLIER_CPRD,
  ID_MANUFACTURER_CPRD,
  AMT_FORGN_CONTENT_CPRD,
  CDE_FORGN_CONTENT_CNTRY_CPRD,
  NUM_SUPPLY_CONTRACT_CPRD,
  DESC_FORGN_CONTENT_CPRD,
  PCT_USED_CPRD,
  STREET_ADR_ID_CPRD
FROM CASEPROD
  --WHERE (CASEPROD.ID_UNIQUE_CPRD >=?)
  --AND (CASEPROD.ID_UNIQUE_CPRD   <=?)
ORDER BY ID_UNIQUE_CPRD,
  ISN;
--
SELECT p.* FROM PARTICIPANT p WHERE (p.ID_PART ='418408') ORDER BY (0+ISN);
--
SELECT MAX(STREET_ADR_ID) FROM PARTICIPANT;
--
UPDATE CASEPART_MU
SET CDE_PART_TYPE_CPRT='',
  PCT_PART_FIN_CPRT   ='2345.87'
WHERE ISN             ='0000378370'
AND MU$ORDER          ='001';
--
SELECT * FROM CASEPART_MU WHERE ISN ='0000378370';
SELECT * FROM CASEPART WHERE ISN ='0000378370';
--
ALTER TABLE CASEPART_MU MODIFY (PCT_PART_FIN_CPRT NUMBER(11,2));
--
SELECT CASEPROD.ISN,
  ID_UNIQUE_CPRD,
  ID_PART_CPRD,
  NO_PROD_SIC_CPRD,
  CDE_NEW_USED_CPRD,
  CDE_BEN_ENVIR_CPRD,
  AMT_PROD_CPRD,
  DESC_PROD_CPRD,
  NO_PROD_NAICS_CPRD,
  ID_SUPPLIER_CPRD,
  ID_MANUFACTURER_CPRD,
  AMT_FORGN_CONTENT_CPRD,
  CDE_FORGN_CONTENT_CNTRY_CPRD,
  NUM_SUPPLY_CONTRACT_CPRD,
  DESC_FORGN_CONTENT_CPRD,
  PCT_USED_CPRD,
  STREET_ADR_ID_CPRD,
  SUPPLIER_STR_ADR_ID_CPRD
FROM CASEPROD
WHERE (CASEPROD.ID_UNIQUE_CPRD >='0000083805')
AND (CASEPROD.ID_UNIQUE_CPRD   <='0000083805')
ORDER BY ID_UNIQUE_CPRD,
  ISN;
--
--
SELECT * FROM caseprod WHERE ID_PART_CPRD = '369195' ORDER BY isn;
--
--
UPDATE caseprod
SET STREET_ADR_ID_CPRD     = '470350',
  SUPPLIER_STR_ADR_ID_CPRD = '2391'
WHERE ID_PART_CPRD         = '369195'
AND isn                    = 127601;
--
COMMIT;
--
--
SELECT * FROM caseprod WHERE ID_PART_CPRD = '369195' ORDER BY isn;
--
SELECT CASEPROD.ISN,
  ID_UNIQUE_CPRD,
  ID_PART_CPRD,
  AMT_PROD_CPRD,
  ID_SUPPLIER_CPRD,
  ID_MANUFACTURER_CPRD,
  AMT_FORGN_CONTENT_CPRD,
  NUM_SUPPLY_CONTRACT_CPRD,
  STREET_ADR_ID_CPRD,
  SUPPLIER_STR_ADR_ID_CPRD
FROM CASEPROD
WHERE (CASEPROD.ID_UNIQUE_CPRD  >='0000083805')
AND (CASEPROD.ID_UNIQUE_CPRD    <='0000083805')
AND (CASEPROD.STREET_ADR_ID_CPRD ='470350')
ORDER BY ID_UNIQUE_CPRD,
  ISN;
--
--
--
--
SELECT * FROM APPL_TRACKING_CONTROL ORDER BY isn DESC; -- where USER_TAC ='conlin' ;
SELECT *
FROM APPL_TRACKING_CONTROL
WHERE USER_TAC  ='conlin'
AND RUNDATN_TAC = '20140715'
AND JOBQUAL_TAC ='005'
ORDER BY isn DESC;
--
--
SELECT CASEPART.ISN,
  ID_PART_CPRT,
  STREET_ADR_ID_CPRT,
  CASEPART_MU.CDE_PART_TYPE_CPRT
FROM CASEPART,
  CASEPART_MU
WHERE (((CASEPART_MU.SPD_UNIQ_TYPE_PART_CP BETWEEN hextoraw('F0F0F0F0F0F8F3F8F8F0F0F3F0404040404040404040') AND hextoraw('F0F0F0F0F0F8F3F8F8F0F0F3F0FFFFFFFF4040404040')))
AND CASEPART.ISN=CASEPART_MU.ISN)
ORDER BY (0+ISN);
--
--
SELECT CASEPART.ISN,
  ID_PART_CPRT,
  STREET_ADR_ID_CPRT,
  CASEPART_MU.CDE_PART_TYPE_CPRT
FROM CASEPART,
  CASEPART_MU
WHERE (((CASEPART_MU.SPD_UNIQ_TYPE_PART_CP BETWEEN hextoraw('F0F0F0F0F0F8F3F8F8F0F0F2F0F5F9F9404040404040') AND hextoraw('F0F0F0F0F0F8F3F8F8F0F0F2F0F5F9F9404040404040')))
AND CASEPART.ISN=CASEPART_MU.ISN)
ORDER BY (0+ISN);
--
--
SELECT CASEPART.ISN,
  ID_PART_CPRT,
  STREET_ADR_ID_CPRT,
  CASEPART_MU.CDE_PART_TYPE_CPRT
FROM CASEPART,
  CASEPART_MU
WHERE (((CASEPART_MU.SPD_UNIQ_TYPE_PART_CP BETWEEN hextoraw('F0F0F0F0F0F8F3F8F8F0F0F2F0404040404040404040') AND hextoraw('F0F0F0F0F0F8F3F8F8F0F0F2F0FFFFFFFF4040404040')))
AND CASEPART.ISN=CASEPART_MU.ISN)
ORDER BY (0+ISN);
--
--
SELECT CASEPART.ISN,
  ID_PART_CPRT,
  STREET_ADR_ID_CPRT,
  CASEPART_MU.CDE_PART_TYPE_CPRT,
  SPD_UNIQ_TYPE_PART_CP
FROM CASEPART,
  CASEPART_MU
WHERE ( CASEPART.ISN   IN (378762,378766)
AND CASEPART.ISN        =CASEPART_MU.ISN)
AND CDE_PART_TYPE_CPRT IS NOT NULL
ORDER BY (0+ISN);
--
--
SELECT DISTINCT m.SPD_UNIQ_TYPE_PART_CP
FROM CASEPART c,
  CASEPART_MU m
WHERE ( c.ISN            IN (378762,378766)
AND c.ISN                 =m.ISN)
AND m.CDE_PART_TYPE_CPRT IS NOT NULL;
--
--
SELECT * FROM CASE_FIELD CF WHERE CF.ID_CASE = 'AP088875XX';
--
SELECT * FROM CASEPART CP WHERE CP.ID_UNIQUE_CPRT = '0000083889';
--
SELECT *
FROM CASEPART_MU
WHERE ISN              IN (378832, 378833)
AND CDE_PART_TYPE_CPRT IS NOT NULL;
--
SELECT PARTICIPANT.ISN,
  ID_PART,
  NME_PART,
  ADDR_FOREIGN_PART,
  ADDR_CITY_PART,
  ADDR_STATE_PART,
  CDE_CNTY_PART,
  STREET_ADR_ID
FROM PARTICIPANT
WHERE (PARTICIPANT.ID_PART     ='599')
AND (PARTICIPANT.STREET_ADR_ID ='330249')
ORDER BY (0+ISN);
--
--
SELECT * FROM CASEPART WHERE CONTACT_ID_CPRT IS NULL;
SELECT * FROM CASE_FIELD CF WHERE CF.ID_CASE = 'AP078807XX';
SELECT DTE_OPERATIVE_CASE FROM CASE_FIELD CF WHERE CF.ID_CASE = 'AP078807XX';
UPDATE CASE_FIELD
SET DTE_OPERATIVE_CASE = '20140717'
WHERE ID_CASE          = 'AP078807XX';
COMMIT;
--
SELECT * FROM case_field WHERE ID_CASE LIKE 'AP08%' ORDER BY ID_CASE DESC;
--
SELECT CASE_FIELD.ISN,
  ID_UNIQUE_CASE,
  ID_CASE,
  CDE_STATUS_CASE,
  DTE_SIGNOFF_CASE,
  ID_ANALYST_SIGNOFF_CASE,
  CDE_EXPORT_MKT_SPEC_IS14373039,
  CDE_REAS_REQ_CASE,
  CDE_TRANS_ORIG_CASE,
  NUM_JOBS_MAINTAINED_CASE,
  NUM_JOBS_ADDITIONAL_CASE,
  DTE_TARGET_ACTION_CASE,
  HELD_STATUS_CASE,
  HELD_COMMENTS_CASE,
  DTE_OPERATIVE_CASE
FROM CASE_FIELD
WHERE ISN='00058150';
