SELECT FINANCE.ISN,
  ID_UNIQUE_FIN,
  OPTION_FIN,
  COMP_FIN,
  AMT_US_FIN,
  AMT_EF_FIN,
  AMT_CONTRACT_PRICE_FIN
FROM FINANCE
WHERE (FINANCE.ID_UNIQUE_FIN ='0000083676')
ORDER BY (0+ISN);
---
SELECT AMT_CONTRACT_PRICE_FIN FROM FINANCE WHERE isn = 90430;
--
UPDATE FINANCE SET AMT_CONTRACT_PRICE_FIN = 2134567890 WHERE isn = 90430;
--
COMMIT;
--
SELECT AMT_US_FIN,
  AMT_EF_FIN,
  AMT_CONTRACT_PRICE_FIN
FROM finance
WHERE isn = 90430;
--
UPDATE FINANCE SET AMT_EF_FIN = 30523547900 WHERE isn = 90430;
--
--
SELECT SUPPLY_CONTRACT.ISN,
  ID_UNIQUE_SCRCT,
  ID_EXPORTER_SCRCT,
  NUM_SUPPLY_CONTRACT_SCRCT,
  AMT_SUPPLY_CONTRACT_SCRCT,
  DTE_SUPPLY_CONTRACT_SCRCT,
  DTE_EXPRT_CERT_RECVD_SCRCT,
  PCT_DISB_SCRCT,
  DTE_CONTRACT_RPT_RECVD_SCRCT,
  EXP_STR_ADR_ID_SCRCT
FROM SUPPLY_CONTRACT
WHERE (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT   IS NOT NULL
AND SUPPLY_CONTRACT.ID_UNIQUE_SCRCT      >='0000083676')
AND (SUPPLY_CONTRACT.ID_UNIQUE_SCRCT     <='0000083676')
AND (SUPPLY_CONTRACT.EXP_STR_ADR_ID_SCRCT ='452228')
ORDER BY ID_UNIQUE_SCRCT,
  ISN;
