--SET serveroutput ON format wrapped;
EXEC tmp_supply_chain_test( '08085546XX0001', 'AA', '12019695', 'CREATE' ) ;
--
SELECT R.NUM_REQ,
  NUM_LOAN_GUAR_REQ,
  CDE_SCHED_REQ,
  '###',
  RG.AMT_RPT_DISB_REQ AMT_RPT_DISB_REQ,
  RG.AMT_RPT_PYMT_REQ AMT_RPT_PYMT_REQ,
  RG.DATE_DUE_REQ DATE_DUE_REQ,
  RG.ISN ISN,
  RG.ISN_REQUEST_REQ ISN_REQUEST_REQ
FROM REQUEST R,
  REQUEST_GRP_SC RG
WHERE R.ISN           = RG.ISN_REQUEST_REQ
AND R.NUM_REQ         = '12019695'
AND NUM_LOAN_GUAR_REQ = '08085546XX0001'
AND CDE_SCHED_REQ     = 'AA' ;
--
--
SELECT DISTINCT R.NUM_REQ
FROM REQUEST R,
  REQUEST_GRP_SC RG
WHERE R.ISN           = RG.ISN_REQUEST_REQ
AND R.NUM_REQ         = '12019695'
AND NUM_LOAN_GUAR_REQ = '08085546XX0001'
AND CDE_SCHED_REQ     = 'AA' ;
--
--
SELECT MAX (NUM_INS_LGI) AS
FROM LG_INSTALLMENT LI
WHERE LI.NUM_LOAN_GUAR_LGI = '08085546XX0001'
AND LI.CDE_SCHED_LGI       = 'AA';
--
--
SELECT * FROM LG_INSTALLMENT WHERE NUM_INS_LGI = 151;
--
--
SELECT ISN AS V_INSTALL_ISN
FROM LG_INSTALLMENT LI
WHERE LI.NUM_LOAN_GUAR_LGI = '08085546XX0001'
AND LI.CDE_SCHED_LGI       = 'AA';
--
--
SELECT *
FROM BAP.REINS_MESSAGE_QUEUE A
  --WHERE A.EIB_MSG_ID = V_EIB_MSG_ID
ORDER BY REINS_MESSAGE_QUEUE_ID;
--
--
---==================================================
SELECT isn,
  ID_CASE,
  CDE_GNTR_RISK_CASE,
  ID_UNIQUE_CASE,
  ID_SUBTYPE_CASE,
  CDE_FCG_CASE,
  CDE_LOAN_SUSP_CASE,
  CDE_STATUS_CASE,
  CDE_TC_GUAR_PGM_CASE,
  CDE_TC_LOAN_PGM_CASE
FROM case_field
WHERE id_case = 'AP086008XC'
AND ID_SUBTYPE_CASE LIKE 'A1%';
--
--UPDATE case_field SET CDE_GNTR_RISK_CASE = 2 WHERE isn = '84129';
--
--
SELECT *
FROM casepart
WHERE ID_UNIQUE_CPRT = '0000083049';
--
--
--DELETE FROM CASEPART_MU WHERE isn IN ( 43695, 43743 );
COMMIT;
ROLLBACK;
--
--
SELECT * FROM CASEPART_MU WHERE isn IN ( 374897 );
--
/*
SELECT a.*
FROM CASEPART_MU a,
CASEPART_MU b
WHERE a.isn = b.isn
AND a.isn  IN ( 379314, 379387, 379388 );
*/
---
---

