
# spring.security.oauth2.resourceserver.opaquetoken.client-id=155392672886-ilt5ico14rbov11r2eftl37r2siealp3.apps.googleusercontent.com
# spring.security.oauth2.resourceserver.opaquetoken.client-secret=NT0hg0rX6p4hQ-jHqYVKL5Jw

spring.security.oauth2.client.registration.google.client-id=155392672886-ilt5ico14rbov11r2eftl37r2siealp3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=NT0hg0rX6p4hQ-jHqYVKL5Jw






