---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nginx.learn.com`) && Headers(`From`, `test@learn.com`)
      kind: Rule
      services:
        - name: nginx-deploy-main
          port: 80
