services:
  cache:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-cache:/data
volumes:
  redis-cache:
    driver: local
    external: false
