

##############################################################################
###############        LinkJob Writer Properties               ###############
##############################################################################
sleep.time.seconds.on.resource.down = 120
db.driver    = com.microsoft.jdbc.sqlserver.SQLServerDriver
db.url       = jdbc:microsoft:sqlserver://NHQSTADEVDB:1433;DatabaseName=TripAlert_Test_2006_08_22
db.usr       = PassRider
db.passwd    = passriderta
db.pool.size = 50 




