package com.learn.selenium.test;


import org.junit.runner.RunWith;

import io.cucumber.junit.Cucumber;
import io.cucumber.junit.CucumberOptions;


/**
 * 1. This will execute all scenarios in same package as the runner.
 * 2. By default glue code is also assumed to be in the same package.
 */
// @formatter:off
@RunWith(Cucumber.class)
/**
 * When no feature path is provided, Cucumber will use the package of theannotated class. For example, if the annotated
 * class is com.example.RunCucumber then features are assumed to be locatedin classpath:com/example.
 */
@CucumberOptions(// monochrome = true,
                 // glue = {"com.learn.selenium.test.GoogleSearchSteps"},
                 // stepNotifications = true,
                 plugin = { "pretty",
                            // html report generated by maven-cucumber-reporting looks better.
                            // "html:target/cucumber-html-report-google-search.htm",
                            "json:target/json-reports/cucumber-json-report-google-search.json"
                          })
// @formatter:on
public class GoogleSearchRunCucumberTest {

}
