######################
#location of log file#
######################

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=### %d [%t] [%-5p](%F:%L) %M() %n%m%n

log4j.appender.other=org.apache.log4j.RollingFileAppender
log4j.appender.other.File=logs/other.txt
log4j.appender.other.layout=org.apache.log4j.PatternLayout
log4j.appender.other.layout.ConversionPattern=%d [%t] [%-5p](%F:%L) %M() %n%m%n
log4j.appender.other.MaxFileSize=2000KB
log4j.appender.other.MaxBackupIndex=10

log4j.appender.com=org.apache.log4j.RollingFileAppender
log4j.appender.com.File=logs/com.txt
log4j.appender.com.layout=org.apache.log4j.PatternLayout
log4j.appender.com.layout.ConversionPattern=%d [%t] [%-5p](%F:%L) %M() %n%m%n
log4j.appender.com.MaxFileSize=2000KB
log4j.appender.com.MaxBackupIndex=10

log4j.appender.learn=org.apache.log4j.RollingFileAppender
log4j.appender.learn.File=logs/learn.txt
log4j.appender.learn.layout=org.apache.log4j.PatternLayout
log4j.appender.learn.layout.ConversionPattern=### %d [%t] [%-5p](%F:%L) %M() %n%m%n
log4j.appender.learn.MaxFileSize=2000KB
log4j.appender.learn.MaxBackupIndex=10

log4j.appender.aps=org.apache.log4j.RollingFileAppender
log4j.appender.aps.File=logs/aps.txt
log4j.appender.aps.layout=org.apache.log4j.PatternLayout
log4j.appender.aps.layout.ConversionPattern=### %d [%t] [%-5p](%F:%L) %M() %n%m%n
log4j.appender.aps.MaxFileSize=2000KB
log4j.appender.aps.MaxBackupIndex=10

# Set root category priority to DEBUG and its only appender to FILE

log4j.logger.other=DEBUG, other, stdout
log4j.logger.com=DEBUG, com, stdout
log4j.logger.com.learn=DEBUG, learn, stdout
log4j.logger.aps=DEBUG, aps, stdout

log4j.additivity.other=false
log4j.additivity.com=false
log4j.additivity.com.learn=false
log4j.additivity.aps=false

log4j.rootLogger=debug, stdout, com, learn

