import React from 'react';
import { BrowserRouter as Router, NavLink, Route, Switch } from 'react-router-dom';
import About from '../About/About';
import './App.scss';
import StateVsMember from '../StateVsMember/StateVsMember';
import Contact from '../Contact';
import FluxCounter from '../FluxCounter/FluxCounter';
import FluxEvent from '../FluxEvent/FluxEvent';
import User from '../User/User';
import Props from '../Props/Props';
import Form from '../Form/Form';
import Event from '../Event/Event';
import Ref from '../Ref/Ref';
import Key from '../Key/Key';

import ComponentAPI from '../ComponentAPI/ComponentAPI';
import ComponentLifeCycle from '../ComponentLifeCycle/ComponentLifeCycle';
import NotFound from '../NotFound/NotFound';

import { Provider } from 'react-redux';
import { connect } from 'react-redux';

import { store } from '../Flux/store/Store';
import { getCounterReselect } from '../Flux/selector/Selectors';


const mapStateToPropsCounter = (state) => {
    console.log('mapStateToPropsCounter', state, state.fluxEventReducer);

    return {
        propCounter: getCounterReselect(state)
    };
};

let DisplayCounterArea = ({ propCounter }) => (
    <span style={{ fontWeight: "bold" }}>{propCounter}</span>
);

DisplayCounterArea = connect(mapStateToPropsCounter)(DisplayCounterArea);



const routing = (
    <Router>
        <div className="nav">
            <ul>
                <li><NavLink activeClassName="active" to="/fluxCounter">FluxCounter</NavLink></li>
                <li><NavLink activeClassName="active" to="/fluxEvent">FluxEvent</NavLink></li>
                <li><NavLink activeClassName="active" to="/stateVsMember">State vs Member</NavLink></li>
                <li><NavLink activeClassName="active" to="/props">Props</NavLink></li>
                <li><NavLink activeClassName="active" to="/componentAPI">ComponentAPI</NavLink></li>
                <li><NavLink activeClassName="active" to="/componentLifeCycle">ComponentLifeCycle</NavLink></li>
                <li><NavLink activeClassName="active" to="/form">Form</NavLink></li>
                <li><NavLink activeClassName="active" to="/event">Event</NavLink></li>
                <li><NavLink activeClassName="active" to="/ref">Ref</NavLink></li>
                <li><NavLink activeClassName="active" to="/key">Key</NavLink></li>

                <li><NavLink activeClassName="active" to="/user/Luke Ma">User</NavLink></li>
                <li><NavLink activeClassName="active" to="/contact">Contact</NavLink></li>
                <li><NavLink activeClassName="active" to="/about">About (<DisplayCounterArea></DisplayCounterArea>)</NavLink></li>
            </ul>
            <hr />
            <Switch>
                <Route path="/" exact component={About} />
                <Route path="/fluxCounter" component={FluxCounter} />
                <Route path="/fluxEvent" component={FluxEvent} />
                <Route path="/stateVsMember" component={StateVsMember} />
                <Route path="/props" component={Props} />
                <Route path="/componentAPI" component={ComponentAPI} />
                <Route path="/componentLifeCycle" component={ComponentLifeCycle} />
                <Route path="/form" component={Form} />
                <Route path="/event" component={Event} />
                <Route path="/ref" component={Ref} />
                <Route path="/key" component={Key} />

                <Route path="/user/:id" component={User} />
                <Route path="/contact" component={Contact} />
                <Route path="/about" component={About} />
                <Route component={NotFound} />
            </Switch>
        </div>
    </Router>
);

class App extends React.Component {
    render() {
        return (
            /**
             * App has the Provider, with store as Provider's props.
             * 
             * This is the center database.
             * 
             * With React Redux, the wrapper classes generated by the connect() function do actually
             * look for props.store if it exists, but it's best if you wrap your root component in 
             * <Provider store={store}> and let React Redux worry about passing the store down. 
             */
            <Provider store={store}>
                <div>
                    {routing}
                    <footer className="footer">
                        <hr/>
                        <div style={{ textAlign: "center" }}>Footer</div>
                    </footer>
                </div>
            </Provider>
        )
    }
}

export default App;