server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/lukekeystore.jks
server.ssl.key-store-password=lukema
server.ssl.key-alias=luke

### default active profile
spring.profiles.default=laptop

# logging.config=classpath:log4j2.xml
logging.config=classpath:@logfile-name-prefix@.xml

# swagger
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
# springfox.documentation.auto-startup=true works for boot 2 (hello 2), but not for boot 3
#     Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.
#                PatternsRequestCondition.getPatterns()" because "this.condition" is null

# springfox for boot 2
# springfox.documentation.auto-startup=false

# springdoc.api-docs.enabled=true is for boot 3
springdoc.api-docs.enabled=true

# Access-Control-Allow-Origin=http://localhost:4200
# Access-Control-Allow-Origin=*
Access-Control-Allow-Origin=@Access-Control-Allow-Origin@

welcome.message=@welcome.message@

server.port=8443

# spring boot < 2.0
# spring.data.rest.basePath=/
# spring boot >= 2.0
# server.servlet.context-path=/my-properties-boot
server.servlet.context-path=@server.servlet.context-path@

# actuator
# https://localhost:8443/                       ### this is default for spring boot 1
# https://localhost:8443/actuator               ### this is default for spring boot 2
# https://localhost:8443/admin                  ### overriding default
# management.endpoints.web.base-path=/admin     ### overriding default

# spring boot 1 property. Repleased with management.endpoints.web.expose=* in spring bott 2.
# management.security.enabled=false

# by default, it only expose info and health. user comma delimiter. * will expose all 13 endpoints.
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans

# shutdown endpoint is disabled by default
# curl -k -i -X POST https://localhost:8443/actuator/shutdown
management.endpoint.shutdown.access=NONE

# never, authorized, always
management.endpoint.health.show-details=always


