kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluentd-clusterrolebinding
  namespace: efk-logging
roleRef:
  kind: ClusterRole
  name: fluentd-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: fluentd-serviceaccount
    namespace: efk-logging
