
log4j.appender.A2=org.apache.log4j.RollingFileAppender
log4j.appender.A2.File=logs/log4j.txt
log4j.appender.A2.Append=false
log4j.appender.A2.MaxFileSize=2MB
log4j.appender.A2.MaxBackupIndex=10
log4j.appender.A2.layout=org.apache.log4j.PatternLayout
log4j.appender.A2.layout.ConversionPattern=%d %-5p %C{1}(%L) %M(): %n%m%n

log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d %-5p %C{1}(%L) %M(): %n%m%n

# log4j.rootLogger=debug, stdout
# log4j.appender.stdout.layout.ConversionPattern=%-5p %C{1}(%L) %M(): %n%m%n

log4j.rootLogger=info, A2

