spring:
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
#      hibernate:
#        jdbc:
#          "[batch_size]": 20
#        boot:
#          "[allow_jdbc_meta_access]": false
      jakarta:
        persistence:
          schema-generation:
            database:
              action: none
            create-database-schema: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: luke
    password: luke
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      continue-on-error: false
      platform: postgres

management:
  endpoint:
    health:
      enabled: true
      show-details: always
      show-components: always
    info:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - health
        - info
