plugins {
    // id 'java'
    // Make it an eclipse project. For cleanEclipse/eclipse tasks.
    // id 'eclipse'
    // id 'eclipse-wtp'
    id 'java-library'
    id 'maven-publish'

    // This is equivalent to specify spring-boot-starter-parent version
    id 'org.springframework.boot' version '2.5.8'
    // spring boot dependency version manager
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
}

apply plugin: 'eclipse'
apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'war'

group 'com.freddiemac.gradle'
version '1.0.1'

bootJar {
    mainClass = 'com.freddiemac.gradle.main.HelloBootGradleMainApplication'
}

def ver="1.2.3"
task hello {
   doLast {
      println "hello ${ver}"
   }
}

repositories {
    // The RepositoryHandler.jcenter() method has been deprecated. This is scheduled to be removed in Gradle 8.0.
    // JFrog announced JCenter's shutdown in February 2021. Use mavenCentral() instead.
    // jcenter()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    // testImplementation 'junit:junit:4.13'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    // api 'org.apache.commons:commons-math3:3.6.1'

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // swagger open api
    // implementation 'org.springdoc:springdoc-openapi-ui:1.5.6'
    implementation 'io.springfox:springfox-boot-starter:3.0.0'

    // devtools
    compileOnly 'org.springframework.boot:spring-boot-devtools'

    // lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    testCompileOnly 'org.projectlombok:lombok'
    testAnnotationProcessor 'org.projectlombok:lombok'

    // mockito java agent to mock final classes and methods
    mockitoAgent("org.mockito:mockito-core") { isTransitive = false }
}

task onlySpecifiesCodeForConfigurationPhase {
    group 'vogella'
    description 'Configuration phase task example.'

    println 'config: I always get printed, even though I am not invoked. From onlySpecifiesCodeForConfigurationPhase'
}

task anotherUnrelatedTask {
    doLast {
        println 'I am in the doLast execution phase from anotherUnrelatedTask'
    }
}

task shortcutTask(dependsOn: 'anotherUnrelatedTask') {

    println 'config: AAAAAAAAAAAAAAAAA from shortcutTask'

    doLast {
        println 'doLast 333333'
    }

    doLast {
        println 'doLast 444444'
    }

    doFirst {
        println 'doFirst 111111'
    }

    doFirst {
        println 'doFirst 222222'
    }
}

// shortcutTask.dependsOn clean, compileJava

compileJava.doFirst { println 'Another action applied to the "compileJava" task' }
compileJava.doLast { println 'Another doLast action is also applied' }

// gradle -q tWP -Pparam=hello
task taskWithParam {
   doLast {
       println "doLast: ${param}"
   }
}

task taskWithParamTest(type: Test) {

   println "config: from taskWithParamTest"

   doLast {
       println "doLast: taskWithParamTest"
   }
}

task taskWithParamCopy(type: Copy) {

   println "config: from taskWithParamCopy"

   doLast {
       println "doLast: taskWithParamCopy"
   }
}

println "1 ${name}"
println "2 ${project.name}"

ext {
    springVersion = "3.1.0.RELEASE"
    emailNotification = "build@master.org"
}

sourceSets.all { ext.purpose = null }

sourceSets {
    main {
        purpose = "production"
    }
    test {
        purpose = "test"
    }
    plugin {
        purpose = "production"
    }
}

tasks.register('printProperties') {

    println 'config: from printProperties'

    doLast {
        println springVersion
        println emailNotification
        sourceSets.matching { it.purpose == "production" }.each { println it.name }
    }
}

def (_, month, year) = "18th June 2009".split()
println "${_} ${month} ${year}"

tasks.register('helloAgain') {

    println "config: from helloAgain"

    doLast {
        println 'hello Again'
    }
}

tasks.register('copy', Copy) {

    println "config: from copy"

    from(file('srcDir'))
    into(buildDir)
}

def anotherCopy = tasks.register('anotherCopy', Copy) {

    println "config: from anotherCopy"

    from(file('srcDir'))
    into(buildDir)
}

// Source - https://stackoverflow.com/a/79668033
// Posted by davidlj95
// Retrieved 2025-12-01, License - CC BY-SA 4.0

def mockitoAgent = configurations.create("mockitoAgent")

tasks.named("test") {
     // ...
     jvmArgs("-javaagent:${mockitoAgent.asPath}")
}

tasks.withType(Jar) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

