create table oa_se_ref (
ref                      varchar2(5) not null,
des                      varchar2(23),
chg_desc                 varchar2(18),
reserved                 varchar2(12),
noc_desc                 varchar2(18),
 FLAG1                   CHAR(1),
 FLAG2                   CHAR(1),
 FLAG3                   CHAR(1),
 FLAG4                   CHAR(1),
 FLAG5                   CHAR(1),
 FLAG6                   CHAR(1),
 FLAG7                   CHAR(1),
 FLAG8                   CHAR(1),
 FLAG9                   CHAR(1),
 FLAG10                  CHAR(1),
 FLAG11                  CHAR(1),
 FLAG12                  CHAR(1),
 FLAG13                  CHAR(1),
 FLAG14                  CHAR(1),
 FLAG15                  CHAR(1),
 FLAG16                  CHAR(1),
 FLAG17                  CHAR(1),
 FLAG18                  CHAR(1),
 FLAG19                  CHAR(1),
 FLAG20                  CHAR(1),
 FLAG21                  CHAR(1),
 FLAG22                  CHAR(1),
 FLAG23                  CHAR(1),
 FLAG24                  CHAR(1),
oasys_type               varchar2(1),
oasys_subtype            varchar2(1),
billing_type             varchar2(1),
market                   varchar2(2) not null,
spending_min             varchar2(4),
spending_max             varchar2(4),
techRestriction          varchar2(1),
filler                   varchar2(40),
nl                  varchar2(1)
)
/
