SELECT
    RowID,
    PropertyID,
    CalendarID,
    InvestorNumber,
    LoanNumber,
    ProspectusID,
    PropertyNumber,
    FS_RequestedItem,
    FS_WFB_Received,
    RR_RequestedItem,
    RR_WFB_Received,
    OSAR_WFB_Received,
    FS_ImageToVendor,
    OSAR_ImageToVendor,
    OSARSpreadVendor
FROM
    ETL_FionaToC3_Staging_Collections;