apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    environment: test
  type: NodePort
  ports:
    - name: my-nginx-port
      port: 8080
      targetPort: 80
  externalIPs:
    - 192.168.1.201
