<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="event">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="organization">
          <xs:annotation>
            <xs:documentation xml:lang="en">Organization</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="4" />
              <xs:maxLength value="255" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="deviceName">
          <xs:annotation>
            <xs:documentation xml:lang="en">Name of device</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="8" />
              <xs:maxLength value="255" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="severity">
          <xs:annotation>
            <xs:documentation xml:lang="en">Severity of event</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Critical" />
              <xs:enumeration value="Major" />
              <xs:enumeration value="Minor" />
              <xs:enumeration value="Notice" />
              <xs:enumeration value="Healthy" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="name">
          <xs:annotation>
            <xs:documentation xml:lang="en">Name of event</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="8" />
              <xs:maxLength value="255" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="message">
          <xs:annotation>
            <xs:documentation xml:lang="en">Event message</xs:documentation>
          </xs:annotation>
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:minLength value="8" />
              <xs:maxLength value="255" />
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element type="xs:dateTime" name="lastDetectedUtc">
          <xs:annotation>
            <xs:documentation xml:lang="en">Last detected datetime UTC</xs:documentation>
          </xs:annotation>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
