FROM centos:latest AS mybase

# stat /usr/sbin/httpd: no such file or dir
# FROM alpine:latest

RUN yum update -y

# 1. httpd
RUN yum -y install httpd

# Cannot find file: /etc/apache2/apache2.conf
# RUN echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf

EXPOSE 80


# 2. ng ui
# ADD Angular Web App
# Use ADD to copy whole directory
ADD ./dist/my-properties-ng /var/www/html/my-properties-ng


# 3. server
# ADD spring boot micro-services
FROM mybase

RUN yum install -y \
   java-1.8.0-openjdk \
   java-1.8.0-openjdk-devel

ENV JAVA_HOME /etc/alternatives



# Do not run mvn build in docker buildx build. Unable to find mvn command.
# RUN mvn -P AWS-Docker -Dmaven.test.skip=true clean package

# war will not work on httpd, because httpd is for static file, non-jsp files only
COPY ./target/MyProperties.war /var/www/html/MyProperties.war

# 4. create logs dir inside docker
RUN mkdir -p /home/ec2-user/dockerlogs

# 5. mount logs dir
# VOLUME /host-path /docker-path
# VOLUME host-value-name /docker-path
VOLUME /home/ec2-user/dockerlogs /home/ec2-user/dockerlogs


# 6. ENTRYPOINT
# CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
