# Cannot build on alpine, because alpine does not have yum 
# FROM alpine:latest AS mybase
FROM centos:latest AS mybase

# alpine does not have yum
RUN yum update -y

RUN yum -y install httpd

FROM mybase

# RUN echo "ServerName 127.0.0.1" >> /etc/apache2/apache2.conf

EXPOSE 80

# Use ADD to copy whole directory
ADD ./dist/my-properties-ng /var/www/html/my-properties-ng

# CMD ["/usr/sbin/httpd", "-D", "FOREGROUND"]

ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]
