
ALTER TABLE OPS$COAST.CS_INTSTMT_BALANCE
   RENAME COLUMN interest_amount TO liab_dly_int;

ALTER TABLE OPS$COAST.CS_INTSTMT_BALANCE
   MODIFY liab_dly_int DEFAULT 0;   
   
ALTER TABLE OPS$COAST.CS_INTSTMT_BALANCE
   ADD (asset_dly_int   NUMBER(38, 5) DEFAULT 0);

ALTER TABLE OPS$COAST.CS_INTSTMT_BALANCE
   ADD (compound_ind        CHAR(1) DEFAULT 'N');

ALTER TABLE OPS$COAST.CS_INTSTMT_BALANCE
   ADD CONSTRAINT check_compound_ind_balance CHECK (compound_ind IN ('N', 'Y'));
