
ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (lch_site   VARCHAR2(50));

ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (lch_protocol   VARCHAR2(10));

ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (lch_user   VARCHAR2(20));

ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (lch_pwd   VARCHAR2(20));

ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (download_lch_flag   CHAR(1) DEFAULT 'N');
   
ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD CONSTRAINT check_download_lch_flag CHECK (download_lch_flag IN ('N', 'Y'));

ALTER TABLE OPS$COAST.CS_CH_FEED
   ADD (legal_entity   VARCHAR2(10));
   
ALTER TABLE OPS$COAST.CS_CH_FEED
   DROP COLUMN TMP_FILE_NAME;







