
ALTER TABLE OPS$COAST.CS_INTSTMT_RAW_DATA
   RENAME COLUMN interest_amount TO liab_dly_int;

ALTER TABLE OPS$COAST.CS_INTSTMT_RAW_DATA
   MODIFY liab_dly_int DEFAULT 0;   
   
ALTER TABLE OPS$COAST.CS_INTSTMT_RAW_DATA
   ADD (asset_dly_int   NUMBER(38, 5) DEFAULT 0);

ALTER TABLE OPS$COAST.CS_INTSTMT_RAW_DATA
   ADD (compound_ind        CHAR(1) DEFAULT 'N');

ALTER TABLE OPS$COAST.CS_INTSTMT_RAW_DATA
   ADD CONSTRAINT check_compound_ind_rd CHECK (compound_ind IN ('N', 'Y'));
