

CREATE OR REPLACE VIEW OPS$COAST.CS_INTSTMT_RES_MOVE_BO_NEW
(
    STATEMENT_ID,
    BALANCE_DATE,
    OPENING_BALANCE,
    CLOSING_BALANCE,
    TOTAL_CREDIT_MOVE,
    TOTAL_DEBIT_MOVE,
    ASSET_DLY_INT,
    LIAB_DLY_INT,
    COMPOUND_IND,
    UPDATE_DATETIME,
    CURRENCY,
    INTEREST_RATE,
    AMOUNT,
    DEBIT,
    CREDIT
)
AS
SELECT R.STATEMENT_ID,R.BALANCE_DATE,R.OPENING_BALANCE,R.CLOSING_BALANCE,R.TOTAL_CREDIT_MOVE,R.TOTAL_DEBIT_MOVE,R.ASSET_DLY_INT,
R.LIAB_DLY_INT,
R.COMPOUND_IND,
R.UPDATE_DATETIME ,
B.CURRENCY,B.INTEREST_RATE, M.AMOUNT, DECODE(SIGN(M.AMOUNT),-1,M.AMOUNT,0) DEBIT, DECODE(SIGN(M.AMOUNT),1,M.AMOUNT,0) CREDIT
FROM
OPS$COAST.CS_INTSTMT_RESULT R,
OPS$COAST.CS_INTSTMT_MOVE M,
OPS$COAST.CS_INTSTMT_BALANCE B
WHERE
R.STATEMENT_ID = B.STATEMENT_ID
AND R.BALANCE_DATE = B.BALANCE_DATE
AND R.STATEMENT_ID = M.STATEMENT_ID(+)
AND R.BALANCE_DATE = M.MOVE_DATE(+);

grant select on OPS$COAST.CS_INTSTMT_RES_MOVE_BO_NEW to BUSOBJRPT;

