DROP TABLE
    OPS$COAST.MO_COMBINED_STMT_RELATION;


CREATE
    TABLE OPS$COAST.MO_COMBINED_STMT_RELATION
    (
        RELATION_ID NUMBER(32),
        STMT_ID NUMBER(32),
        CUSTOMER_UCN VARCHAR2(12),
        CUSTOMER_SPN VARCHAR2(20),
        COAST_AGREEMENT_NUMBER NUMBER(22),
        GMI_ACCT_NUMBER VARCHAR2(20),
        UPDATE_DATETIME DATE
    );
