
DROP TABLE
    OPS$COAST.MO_COMBINED_STMT_SETUP;


CREATE
    TABLE OPS$COAST.MO_COMBINED_STMT_SETUP
    (
        STMT_ID NUMBER(32),
        CUSTOMER_UCN VARCHAR2(12),
        CUSTOMER_SPN VARCHAR2(20),
        STMT_NAME VARCHAR2(100),
        STMT_STATUS VARCHAR2(10),
        CSR_ID NUMBER(32),
        REGION VARCHAR2(20),
        NOTIFICATION_DEADLINE VARCHAR2(20),
        STP_LEVEL VARCHAR2(20),
        CODED_STATEMENT_REQUIRED NUMBER(1),
        CODED_STATEMENT_NAME VARCHAR2(100),
        PASSWORD_REQUIRED NUMBER(1),
        AUTOGENERATE_PASSWORD NUMBER(1),
        PASSWORD VARCHAR2(40),
        AUTO_INCLUDE_GMI_ACCOUNTS NUMBER(1),
        AUTO_INCLUDE_COAST_AGR NUMBER(1),
        FX_SETTLEMENT VARCHAR2(20),
        DERIVATIVES_SETTLEMENT VARCHAR2(20),
        UPDATE_DATETIME DATE
    );


ALTER TABLE OPS$COAST.MO_COMBINED_STMT_SETUP
   ADD CONSTRAINT MO_COMBINED_STMT_SETUP_PK PRIMARY KEY (STMT_ID);

--ALTER TABLE OPS$COAST.MO_COMBINED_STMT_SETUP ADD CONSTRAINT constraint_name UNIQUE (column1, column2, ... column_n);

--CREATE SEQUENCE CFTC_STMT_ID_SEQ;

