

alter table CS_BNK_NM_SHORT_FRM add (STMT_BANK_NAME varchar2(15));
  
update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'JPM COMM CANADA' where SHRT_BNK_NM = 'JPMCCC';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'JPMSJ' where SHRT_BNK_NM = 'JPMSJ';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'BSAAIL' where SHRT_BNK_NM = 'BSAAIL';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'MLP HOLDINGS' where SHRT_BNK_NM = 'MLP';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'BSFP INC' where SHRT_BNK_NM = 'BSFP';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'JPMBDP' where SHRT_BNK_NM = 'JPMBDP';

update CS_BNK_NM_SHORT_FRM set STMT_BANK_NAME = 'JPMSFEL' where SHRT_BNK_NM = 'JPMSFEL';

