
/*
select * 
from CS_INTSTMT_RAW_DATA
where BATCH_NUMBER = 216263
and ACCOUNT_NUMBER = '00579847A'
order by date_time asc
*/


select 
count(*),
BRANCH,
ACCOUNT_NUMBER,
--CUSTOMER_NAME,
DATE_TIME,
CAPITALIZED_DAILY,
--UPDATE_DATETIME,
DAILY_OPENING_BALANCE,
DAILY_CLOSING_BALANCE,
MOVE_AMOUNT,
INTEREST_AMOUNT,
INTEREST_RATE
from CS_INTSTMT_RAW_DATA
--where date_time = to_date('2009-10-11', 'YYYY-MM-DD')
--where date_time = to_date('2010-01-11', 'YYYY-MM-DD')
where account_number = '00033538A'
group by 
BRANCH,
ACCOUNT_NUMBER,
--CUSTOMER_NAME,
DATE_TIME,
CAPITALIZED_DAILY,
--UPDATE_DATETIME,
DAILY_OPENING_BALANCE,
DAILY_CLOSING_BALANCE,
MOVE_AMOUNT,
INTEREST_AMOUNT,
INTEREST_RATE
order by account_number, date_time


