
/*
INSERT INTO CS_STREAM_QUEUE
(RUN_CATEGORY, SEQUENCE, STATUS, ARG1, ARG2, COB_DATE)
VALUES
(?,
    (SELECT NVL(MAX(SEQUENCE)+1, 0)
     FROM CS_STREAM_QUEUE
     WHERE RUN_CATEGORY=?),
       ?, ?, ?, SYSDATE)
*/

/*
SELECT NVL(MAX(SEQUENCE)+1, 0)
     FROM CS_STREAM_QUEUE
     WHERE RUN_CATEGORY='CFCS_STMT'
*/

--select * from CS_STREAM_QUEUE where RUN_CATEGORY = 'CFTC_STMT';

--delete from CS_STREAM_QUEUE where RUN_CATEGORY = 'CFTC_STMT';


select status from CS_STREAM_QUEUE where RUN_CATEGORY = 'CFTC_STMT';

