/*
INSERT
INTO
    MO_COMBINED_STMT_SETUP
    (
        STMT_ID,
        STMT_NAME,
        CSR,
        REGION,
        NOTIFICATION_DEADLINE,
        STP_LEVEL,
        CODED_STATEMENT_REQUIRED,
        CODED_STATEMENT_NAME,
        PASSWORD_REQUIRED,
        AUTOGENERATE_PASSWORD,
        PASSWORD,
        AUTO_INCLUDE_GMI_ACCOUNTS,
        AUTO_INCLUDE_COAST_AGR,
        FX_SETTLEMENT,
        DERIVATIVES_SETTLEMENT,
        UPDATE_DATETIME
    )
    VALUES
    (
        #statementTemplateId#,
        #statementName#,
        #csr#,
        #region#,
        #notificationDeadline#,
        #stpLevel#,
        #codedStatementRequired#,
        #codedStatementName#,
        #passwordRequired#,
        #autoGeneratePassword#,
        #password#,
        #autoIncludeNewGmiAccounts#,
        #autoIncludeNewCoastAgreement#,
        #fxSettlementDisplayType#,
        #derivativesSettlementDisplayType#,
        sysdate
    ) ;
*/

INSERT
INTO
    MO_COMBINED_STMT_SETUP
    (
        STMT_ID,
        STMT_NAME
    )
    VALUES
    (
        CFTC_STMT_ID_SEQ.NEXTVAL,
        'Test'
    ) ;