

------------------------------------------------------
-- CS_FILE_SETUP
DELETE FROM  OPS$COAST.CS_FILE_SETUP
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


-- CS_FILE_SETUP IM
INSERT INTO OPS$COAST.CS_FILE_SETUP
(
    SOURCE_FEED_NAME,
    DATA_FILE_NAME,
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE,
    SCRIPT_TO_RUN_BEFORE_LOAD,
    SCRIPT_TO_MAP_FIELDS,
    LOAD_STATUS_TABLE,
    INTERFACE_NAME
)
SELECT
    'LCHEMEAIAJPMSL',
    'LCHEMEAIAJPMSL',
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    sysdate,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE,
    SCRIPT_TO_RUN_BEFORE_LOAD,
    SCRIPT_TO_MAP_FIELDS,
    LOAD_STATUS_TABLE,
    INTERFACE_NAME
FROM  OPS$COAST.CS_FILE_SETUP
WHERE SOURCE_FEED_NAME = 'LCHEMEAIA';


-- CS_FILE_SETUP VM
INSERT INTO OPS$COAST.CS_FILE_SETUP
(
    SOURCE_FEED_NAME,
    DATA_FILE_NAME,
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE,
    SCRIPT_TO_RUN_BEFORE_LOAD,
    SCRIPT_TO_MAP_FIELDS,
    LOAD_STATUS_TABLE,
    INTERFACE_NAME
)
SELECT
    'LCHEMEAMTMJPMSL',
    'LCHEMEAMTMJPMSL',
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    sysdate,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE,
    SCRIPT_TO_RUN_BEFORE_LOAD,
    SCRIPT_TO_MAP_FIELDS,
    LOAD_STATUS_TABLE,
    INTERFACE_NAME
FROM  OPS$COAST.CS_FILE_SETUP
WHERE SOURCE_FEED_NAME = 'LCHEMEAMTM';


------------------------------------------------------
-- CS_FILE_ID
DELETE FROM  OPS$COAST.CS_FILE_ID
WHERE FILE_ID = 'LCHEMEAIAJPMSL'
OR FILE_ID = 'LCHEMEAMTMJPMSL';


-- CS_FILE_ID IM
INSERT INTO OPS$COAST.CS_FILE_ID
(
    FILE_ID,
    LOAD_TYPE,
    REGION,
    COUNTRY,
    EXP_TIME,
    TIME_DIFF,
    ALARM_FLAG,
    EFFECTIVE_DATE,
    DESCRIPTION,
    CONTRACT_FILE_FLG,
    FILE_GROUP,
    KAPITAL_FILE_FLG,
    INTRADAY_FEED,
    SENDER,
    DEAL_LINK,
    SERVER,
    PRIMARY_DATABASE,
    CRDER_BUY_SELL_FLG,
    FEED_CONVERGE_STATUS
)
SELECT
    'LCHEMEAIAJPMSL',
    LOAD_TYPE,
    REGION,
    COUNTRY,
    EXP_TIME,
    TIME_DIFF,
    ALARM_FLAG,
    to_date('2011-01-16', 'yyyy-mm-dd'),
    DESCRIPTION,
    CONTRACT_FILE_FLG,
    FILE_GROUP,
    KAPITAL_FILE_FLG,
    INTRADAY_FEED,
    SENDER,
    DEAL_LINK,
    SERVER,
    PRIMARY_DATABASE,
    CRDER_BUY_SELL_FLG,
    FEED_CONVERGE_STATUS
FROM  OPS$COAST.CS_FILE_ID
WHERE FILE_ID = 'LCHEMEAIA'; 


-- CS_FILE_ID VM
INSERT INTO OPS$COAST.CS_FILE_ID
(
    FILE_ID,
    LOAD_TYPE,
    REGION,
    COUNTRY,
    EXP_TIME,
    TIME_DIFF,
    ALARM_FLAG,
    EFFECTIVE_DATE,
    DESCRIPTION,
    CONTRACT_FILE_FLG,
    FILE_GROUP,
    KAPITAL_FILE_FLG,
    INTRADAY_FEED,
    SENDER,
    DEAL_LINK,
    SERVER,
    PRIMARY_DATABASE,
    CRDER_BUY_SELL_FLG,
    FEED_CONVERGE_STATUS
)
SELECT
    'LCHEMEAMTMJPMSL',
    LOAD_TYPE,
    REGION,
    COUNTRY,
    EXP_TIME,
    TIME_DIFF,
    ALARM_FLAG,
    to_date('2011-01-16', 'yyyy-mm-dd'),
    DESCRIPTION,
    CONTRACT_FILE_FLG,
    FILE_GROUP,
    KAPITAL_FILE_FLG,
    INTRADAY_FEED,
    SENDER,
    DEAL_LINK,
    SERVER,
    PRIMARY_DATABASE,
    CRDER_BUY_SELL_FLG,
    FEED_CONVERGE_STATUS
FROM  OPS$COAST.CS_FILE_ID
WHERE FILE_ID = 'LCHEMEAMTM'; 


------------------------------------------------------
-- CV_FILE_ID
DELETE FROM  OPS$COAST.CV_FILE_ID
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


-- CV_FILE_ID IM
INSERT INTO OPS$COAST.CV_FILE_ID
(
    SOURCE_FEED_NAME,
    LOAD_TYPE,
    REGION,
    COUNTRY,
    PRODUCT_CODE,
    EFFECTIVE_DATE,
    DECOMMISION_DATE,
    DESCRIPTION,
    SUPPLYING_SYSTEM,
    PROVIDING_SYSTEM,
    SLA,
    FILE_GROUP,
    ALARM_FLAG,
    INPUT_ID,
    UPDATE_DATETIME,
    DEPENDENCY,
    TOLERANCE_PCT,
    TRADE_SUPPLY_NAME,
    CASHFLOW_SUPPLY_NAME
)
SELECT
    'LCHEMEAIAJPMSL',
    LOAD_TYPE,
    REGION,
    COUNTRY,
    PRODUCT_CODE,
    to_date('2011-01-16', 'yyyy-mm-dd'),
    DECOMMISION_DATE,
    DESCRIPTION,
    SUPPLYING_SYSTEM,
    PROVIDING_SYSTEM,
    SLA,
    FILE_GROUP,
    ALARM_FLAG,
    INPUT_ID,
    sysdate,
    DEPENDENCY,
    TOLERANCE_PCT,
    TRADE_SUPPLY_NAME,
    CASHFLOW_SUPPLY_NAME
FROM  OPS$COAST.CV_FILE_ID WHERE SOURCE_FEED_NAME = 'LCHEMEAIA';


-- CV_FILE_ID VM
INSERT INTO OPS$COAST.CV_FILE_ID
(
    SOURCE_FEED_NAME,
    LOAD_TYPE,
    REGION,
    COUNTRY,
    PRODUCT_CODE,
    EFFECTIVE_DATE,
    DECOMMISION_DATE,
    DESCRIPTION,
    SUPPLYING_SYSTEM,
    PROVIDING_SYSTEM,
    SLA,
    FILE_GROUP,
    ALARM_FLAG,
    INPUT_ID,
    UPDATE_DATETIME,
    DEPENDENCY,
    TOLERANCE_PCT,
    TRADE_SUPPLY_NAME,
    CASHFLOW_SUPPLY_NAME
)
SELECT
    'LCHEMEAMTMJPMSL',
    LOAD_TYPE,
    REGION,
    COUNTRY,
    PRODUCT_CODE,
    to_date('2011-01-16', 'yyyy-mm-dd'),
    DECOMMISION_DATE,
    DESCRIPTION,
    SUPPLYING_SYSTEM,
    PROVIDING_SYSTEM,
    SLA,
    FILE_GROUP,
    ALARM_FLAG,
    INPUT_ID,
    sysdate,
    DEPENDENCY,
    TOLERANCE_PCT,
    TRADE_SUPPLY_NAME,
    CASHFLOW_SUPPLY_NAME
FROM  OPS$COAST.CV_FILE_ID WHERE SOURCE_FEED_NAME = 'LCHEMEAMTM';


------------------------------------------------------
-- CV_FEED_DATA_FILE_SETUP
DELETE FROM  OPS$COAST.CV_FEED_DATA_FILE_SETUP
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


-- CV_FEED_DATA_FILE_SETUP IM
INSERT INTO OPS$COAST.CV_FEED_DATA_FILE_SETUP
(
    SOURCE_FEED_NAME,
    DATA_FILE_NAME,
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE
)
SELECT
    'LCHEMEAIAJPMSL',
    'LCHEMEAIAJPMSL',
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    sysdate,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE
FROM  OPS$COAST.CV_FEED_DATA_FILE_SETUP WHERE SOURCE_FEED_NAME = 'LCHEMEAIA';


-- CV_FEED_DATA_FILE_SETUP VM
INSERT INTO OPS$COAST.CV_FEED_DATA_FILE_SETUP
(
    SOURCE_FEED_NAME,
    DATA_FILE_NAME,
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE
)
SELECT
    'LCHEMEAMTMJPMSL',
    'LCHEMEAMTMJPMSL',
    MAIN_OR_INTER,
    LOADING_SCRIPT_NAME,
    LOAD_TABLE_NAME,
    STATUS_CODE,
    INPUT_ID,
    sysdate,
    DATE_FORMAT,
    CHECK_TABLE_ROWS,
    LOAD_TABLE_TYPE,
    FIELD_DELIMITER,
    HEADER_FOOTER,
    IS_ADD_COB_DATE,
    IS_ADD_FEED_NAME,
    IS_FLAG_FILE
FROM  OPS$COAST.CV_FEED_DATA_FILE_SETUP WHERE SOURCE_FEED_NAME = 'LCHEMEAMTM';


------------------------------------------------------
-- CV_FEED_DATA_FILE_SETUP
DELETE FROM  OPS$COAST.CV_FEED_LOAD_BOX_SETUP
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


-- CV_FEED_LOAD_BOX_SETUP IM
INSERT INTO OPS$COAST.CV_FEED_LOAD_BOX_SETUP
(
    SOURCE_FEED_NAME,
    JOB_SEQUENCE,
    JOB_NAME,
    SHORT_FEED_NAME,
    MAIN_SCRIPT,
    SQL_SCRIPT,
    STAGING_TABLE,
    RDR_UPDATE_SCRIPT,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME
)
SELECT
    'LCHEMEAIAJPMSL',
    JOB_SEQUENCE,
    JOB_NAME,
    'LCHIAL',
    MAIN_SCRIPT,
    SQL_SCRIPT,
    STAGING_TABLE,
    RDR_UPDATE_SCRIPT,
    STATUS_CODE,
    INPUT_ID,
    sysdate
FROM  OPS$COAST.CV_FEED_LOAD_BOX_SETUP WHERE SOURCE_FEED_NAME = 'LCHEMEAIA';


-- CV_FEED_LOAD_BOX_SETUP VM
INSERT INTO OPS$COAST.CV_FEED_LOAD_BOX_SETUP
(
    SOURCE_FEED_NAME,
    JOB_SEQUENCE,
    JOB_NAME,
    SHORT_FEED_NAME,
    MAIN_SCRIPT,
    SQL_SCRIPT,
    STAGING_TABLE,
    RDR_UPDATE_SCRIPT,
    STATUS_CODE,
    INPUT_ID,
    UPDATE_DATETIME
)
SELECT
    'LCHEMEAMTMJPMSL',
    JOB_SEQUENCE,
    JOB_NAME,
    'LCHMTML',
    MAIN_SCRIPT,
    SQL_SCRIPT,
    STAGING_TABLE,
    RDR_UPDATE_SCRIPT,
    STATUS_CODE,
    INPUT_ID,
    sysdate
FROM  OPS$COAST.CV_FEED_LOAD_BOX_SETUP WHERE SOURCE_FEED_NAME = 'LCHEMEAMTM';



COMMIT;

