
DROP TABLE
    OPS$COAST.LUKE_TEST;


CREATE
    TABLE OPS$COAST.LUKE_TEST
    (
        Name VARCHAR2(20),
        Age NUMBER(32)
    );

    
CREATE OR REPLACE PUBLIC SYNONYM LUKE_TEST FOR OPS$COAST.LUKE_TEST;

GRANT SELECT ON OPS$COAST.LUKE_TEST TO COAST_READ_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$COAST.LUKE_TEST TO COAST_UPDATE_ROLE;

INSERT INTO LUKE_TEST
(Name, Age)
VALUES
('Luke', 37);

INSERT INTO LUKE_TEST
(Name, Age)
VALUES
('John', 23);

commit;
