DROP TABLE OPS$COAST.MO_COMBINED_CONTACT_RELATION CASCADE CONSTRAINTS;

CREATE TABLE OPS$COAST.MO_COMBINED_CONTACT_RELATION
(
  RELATIONSHIP_RECORD_ID  NUMBER(38)            NOT NULL,
  CALCULATION_TYPE        VARCHAR2(20 BYTE)     NOT NULL,
  STMT_ID        NUMBER(38)            NOT NULL,
  CONTACT_RECORD_ID       NUMBER(38)            NOT NULL,
  RELATION_TYPE           VARCHAR2(20 BYTE)     NOT NULL,
  STATUS_CODE             VARCHAR2(1 BYTE),
  INPUT_ID                VARCHAR2(45 BYTE),
  UPDATE_DATETIME         DATE
)
TABLESPACE TS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

/*
CREATE INDEX OPS$COAST.IDX1_MO_COMBINED_CONTACT_RELATION ON OPS$COAST.MO_COMBINED_CONTACT_RELATION
(STMT_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX OPS$COAST.IDX2_MO_COMBINED_CONTACT_RELTN ON OPS$COAST.MO_COMBINED_CONTACT_RELATION
(RELATIONSHIP_RECORD_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX OPS$COAST.IDX3_MO_COMBINED_CONTACT_RELTN ON OPS$COAST.MO_COMBINED_CONTACT_RELATION
(STMT_ID, CONTACT_RECORD_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX OPS$COAST.IDX4_MO_COMBINED_CONTACT_RELTN ON OPS$COAST.MO_COMBINED_CONTACT_RELATION
(CONTACT_RECORD_ID, STMT_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

DROP PUBLIC SYNONYM MO_COMBINED_CONTACT_RELTN;

CREATE PUBLIC SYNONYM MO_COMBINED_CONTACT_RELTN FOR OPS$COAST.MO_COMBINED_CONTACT_RELTN;


GRANT SELECT ON OPS$COAST.MO_COMBINED_CONTACT_RELTN TO ANCHOR;

--GRANT SELECT ON OPS$COAST.MO_COMBINED_CONTACT_RELATION TO ANCLINKUSER;

GRANT SELECT ON OPS$COAST.MO_COMBINED_CONTACT_RELTN TO COAST_READ_ROLE;


GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$COAST.MO_COMBINED_CONTACT_RELTN TO COAST_UPDATE_ROLE;
*/

commit;