SELECT DISTINCT
    CUSTOMER_UCN,
    CUSTOMER_FULL_NAME,
    CUSTOMER_SPN
FROM
    CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
    STATUS_CODE ='A'
AND AGREEMENT_PROCESSING_STATUS ='ACTIVE'
AND
    (
        CUSTOMER_FULL_NAME IS NULL
     OR CUSTOMER_SPN IS NULL
    )
AND CALCULATION_TYPE = 'DERIVATIVES'
AND NOT EXISTS
    (
        SELECT
            1
        FROM
            CS_FIREWALL_RULE FW
        WHERE
            CS_UCN_LEAD_OFFICE = FW.BANK_UCN
        AND GROUP_4_VISIBILITY = 'N'
    )
ORDER BY
    CUSTOMER_FULL_NAME