DROP TABLE OPS$COAST.MO_COMBINED_STMT_CONTACT CASCADE CONSTRAINTS;

CREATE TABLE OPS$COAST.MO_COMBINED_STMT_CONTACT
(
  CONTACT_RECORD_ID         NUMBER(38)          NOT NULL,
  STMT_ID                      NUMBER(38)          NOT NULL,
  STATUS_CODE               VARCHAR2(1 BYTE),
  INPUT_ID                  VARCHAR2(45 BYTE),
  UPDATE_DATETIME           DATE,
  APPROVER_ID               VARCHAR2(45 BYTE),
  APPROVAL_UPDATE_DATETIME  DATE
)
TABLESPACE TS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE INDEX OPS$COAST.MO_COMBINED_STMT_CONTACT_IX1 ON OPS$COAST.MO_COMBINED_STMT_CONTACT
(CONTACT_RECORD_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX OPS$COAST.MO_COMBINED_STMT_CONTACT_IX3 ON OPS$COAST.MO_COMBINED_STMT_CONTACT
(STMT_ID, CONTACT_RECORD_ID)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


CREATE INDEX OPS$COAST.IDX2_MO_COMBINED_STMT_CONTACT ON OPS$COAST.MO_COMBINED_STMT_CONTACT
(CONTACT_RECORD_ID, STATUS_CODE)
LOGGING
TABLESPACE TS_INDEX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


--DROP PUBLIC SYNONYM MO_COMBINED_STMT_CONTACT;

CREATE PUBLIC SYNONYM MO_COMBINED_STMT_CONTACT FOR OPS$COAST.MO_COMBINED_STMT_CONTACT;


GRANT SELECT ON OPS$COAST.MO_COMBINED_STMT_CONTACT TO COAST_READ_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON OPS$COAST.MO_COMBINED_STMT_CONTACT TO COAST_UPDATE_ROLE;

commit;