

SELECT
    'drn' as key, OPS$COAST.CS_RUN_STATUS.CEL_RUN_NUMBER
FROM
    OPS$COAST.CS_RUN_STATUS
WHERE
    OPS$COAST.CS_RUN_STATUS.RUN_CATEGORY = 'CFTC_STMT'
AND OPS$COAST.CS_RUN_STATUS.SUCCESS_FLG = 'Y'
AND OPS$COAST.CS_RUN_STATUS.RUN_NUMBER = 261483

union all

SELECT
    'rn', OPS$COAST.CS_RUN_STATUS.CEL_RUN_NUMBER
FROM
    OPS$COAST.CS_RUN_STATUS
WHERE
    OPS$COAST.CS_RUN_STATUS.RUN_CATEGORY = 'CFTC_STMT'
AND OPS$COAST.CS_RUN_STATUS.SUCCESS_FLG = 'Y'
AND OPS$COAST.CS_RUN_STATUS.RUN_NUMBER = 261483;
