SELECT
    ---DISTINCT
    CS_RUN_STATUS_DETAIL.run_number drn,
    MO_CFTC_STMT_SETUP.run_number rn,
    v.*,
    'RELATIONSHIP',
    MO_CFTC_STMT_RELATION.*,
    'DETAIL',
    CS_RUN_STATUS_DETAIL.*,
    'SETUP',
    MO_CFTC_STMT_SETUP.*
FROM
    MO_COMBINED_MOVE_SUMMARY_VIEW v,
    CS_RUN_STATUS_DETAIL,
    MO_CFTC_STMT_RELATION,
    MO_CFTC_STMT_SETUP
WHERE
    v.FEED_ID = 261457
AND v.cob_date = '23-may-2011'
AND CS_RUN_STATUS_DETAIL.run_number = 261464
AND MO_CFTC_STMT_SETUP.run_number =261483
AND
    (
        v.SRC_CLIENT_ACCOUNT = '11274892'
     OR v.SRC_CLIENT_ACCOUNT = '11266371'
    )
AND
    (
        CS_RUN_STATUS_DETAIL.COB_DATE= v.COB_DATE
    AND CS_RUN_STATUS_DETAIL.FEED_ID= v.FEED_ID
    )
AND
    (
        MO_CFTC_STMT_RELATION.RUN_NUMBER= MO_CFTC_STMT_SETUP.RUN_NUMBER
    AND MO_CFTC_STMT_RELATION.STMT_ID= MO_CFTC_STMT_SETUP.STMT_ID
    )
AND
    (
        MO_CFTC_STMT_RELATION.CLIENT_ACCT_NUMBER= v.SRC_CLIENT_ACCOUNT
    AND MO_CFTC_STMT_RELATION.CLIENT_SOURCE= v.SOURCE
    )