SELECT
    R.STMT_ID,
    C.CUSTOMER_FULL_NAME,
    R.CUSTOMER_UCN,
    R.CUSTOMER_SPN,
    R.COAST_AGRREMENT_NUMBER,
    R.GMI_ACCT_NUMBER
FROM
    CS_COL_CUSTOMER_SETUP C,
    MO_COMBINED_STMT_RELATION R
WHERE
    C.CUSTOMER_UCN = R.CUSTOMER_UCN