
SELECT
    C.CUSTOMER_FULL_NAME,
    R.COAST_AGRREMENT_NUMBER,
    R.GMI_ACCT_NUMBER,
    R.UPDATE_DATETIME
FROM
    CS_COL_CUSTOMER_SETUP C,
    MO_COMBINED_STMT_RELATION R,
    MO_COMBINED_STMT_SETUP T
WHERE
    C.CUSTOMER_UCN = R.UCN
AND T.STMT_ID = R.STMT_ID;