

SELECT
    STMT_ID,
    STMT_NAME,
    CSR,
    REGION,
    NOTIFICATION_DEADLINE,
    STP_LEVEL,
    CODED_STATEMENT_REQUIRED,
    CODED_STATEMENT_NAME,
    PASSWORD_REQUIRED,
    AUTOGENERATE_PASSWORD,
    PASSWORD,
    AUTO_INCLUDE_GMI_ACCOUNTS,
    AUTO_INCLUDE_COAST_AGR,
    FX_SETTLEMENT,
    DERIVATIVES_SETTLEMENT,
    UPDATE_DATETIME
FROM OPS$COAST.MO_COMBINED_STMT_SETUP;


--DELETE FROM OPS$COAST.MO_COMBINED_STMT_SETUP;
