SELECT DISTINCT
    C.CUSTOMER_FULL_NAME,
    G.CUSTOMER_SPN,
    G.ACCOUNT,
    G.ACCOUNT_MARGIN_RULE,
    C.AGREEMENT_NUMBER,
    G.COB_DATE
FROM
    CS_COL_CUSTOMER_SETUP C
LEFT JOIN MO_GMI_ACCOUNT_VIEW G
ON
    G.CUSTOMER_SPN = C.CUSTOMER_SPN
WHERE
    C.STATUS_CODE = 'A'
AND C.AGREEMENT_PROCESSING_STATUS = 'ACTIVE'
AND G.COB_DATE =
    (
        SELECT
            MAX(COB_DATE)
        FROM
            MO_GMI_ACCOUNT_VIEW
    )
ORDER BY
    1,
    2,
    3