
/*
select distinct ACCOUNT, ACCOUNT_MARGIN_RULE from MO_GMI_ACCOUNT_VIEW
where COB_DATE = (
select max(input_datetime) from cs_load_status where file_id = 'GMIMARGIN' and load_datetime is not
null
)
*/
/*
select distinct
CUSTOMER_SPN,
CUSTOMER_UCN,
AGREEMENT_NUMBER
from CS_COL_CUSTOMER_SETUP;
*/
/*
DECLARE
vName varchar2(20) := 'FIFI%';
vCType varchar2(20) := 'DERIVATIVES';
ucn CS_COL_CUSTOMER_SETUP.CUSTOMER_UCN%type;
name CS_COL_CUSTOMER_SETUP.CUSTOMER_FULL_NAME%type;
spn CS_COL_CUSTOMER_SETUP.CUSTOMER_SPN%type;
BEGIN
SELECT DISTINCT
CUSTOMER_UCN,
CUSTOMER_FULL_NAME,
CUSTOMER_SPN
INTO
ucn,
name,
spn
FROM
CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
STATUS_CODE = 'A'
AND AGREEMENT_PROCESSING_STATUS = 'ACTIVE'
AND CUSTOMER_FULL_NAME LIKE vName
--ESCAPE '\'
AND CALCULATION_TYPE = vCType
AND NOT EXISTS
(
SELECT
1
FROM
CS_FIREWALL_RULE FW
WHERE
CS_UCN_LEAD_OFFICE = FW.BANK_UCN
AND GROUP_4_VISIBILITY = 'N'
)
AND rownum = 1
ORDER BY
CUSTOMER_FULL_NAME;
DBMS_OUTPUT.put_line(ucn || '<--->' || name || '<--->' || spn);
END;
*/
/*
DECLARE
vName varchar2(20) := 'FIFI%';
vCType varchar2(20) := 'DERIVATIVES';
ucn CS_COL_CUSTOMER_SETUP.CUSTOMER_UCN%type;
name CS_COL_CUSTOMER_SETUP.CUSTOMER_FULL_NAME%type;
spn CS_COL_CUSTOMER_SETUP.CUSTOMER_SPN%type;
CURSOR cur IS
SELECT DISTINCT
CUSTOMER_UCN,
CUSTOMER_FULL_NAME,
CUSTOMER_SPN
FROM
CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
STATUS_CODE = 'A'
AND AGREEMENT_PROCESSING_STATUS = 'ACTIVE'
AND CUSTOMER_FULL_NAME LIKE vName
--ESCAPE '\'
AND CALCULATION_TYPE = vCType
AND NOT EXISTS
(
SELECT
1
FROM
CS_FIREWALL_RULE FW
WHERE
CS_UCN_LEAD_OFFICE = FW.BANK_UCN
AND GROUP_4_VISIBILITY = 'N'
)
ORDER BY
CUSTOMER_FULL_NAME;
BEGIN
OPEN cur;
LOOP
FETCH cur INTO
ucn,
name,
spn;
EXIT WHEN cur%NOTFOUND OR cur%NOTFOUND IS NULL;
DBMS_OUTPUT.put_line(ucn || '<--->' || name || '<--->' || spn);
END LOOP;
CLOSE cur;
END;
*/
-- SELECT distinct CUSTOMER_UCN, CUSTOMER_FULL_NAME, CUSTOMER_SPN     FROM CS_COL_CUSTOMER_SETUP
-- CUST_SETUP     WHERE  STATUS_CODE ='A' AND AGREEMENT_PROCESSING_STATUS ='ACTIVE'       AND
-- CUSTOMER_FULL_NAME LIKE ? ESCAPE '\'        AND        CALCULATION_TYPE = ?        AND
-- NOT EXISTS (SELECT 1 FROM CS_FIREWALL_RULE FW WHERE CS_UCN_LEAD_OFFICE = FW.BANK_UCN         AND
-- GROUP_4_VISIBILITY = 'N')                 ORDER BY CUSTOMER_FULL_NAME;
-- Parameters: [FIFI%, DERIVATIVES]
/*
SELECT DISTINCT
    CUSTOMER_UCN,
    CUSTOMER_FULL_NAME,
    CUSTOMER_SPN
FROM
    CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
    STATUS_CODE ='A'
AND AGREEMENT_PROCESSING_STATUS ='ACTIVE'
AND CUSTOMER_SPN LIKE ?
AND CALCULATION_TYPE = ?
AND NOT EXISTS
    (
        SELECT
            1
        FROM
            CS_FIREWALL_RULE FW
        WHERE
            CS_UCN_LEAD_OFFICE = FW.BANK_UCN
        AND GROUP_4_VISIBILITY = 'N'
    )
ORDER BY
    CUSTOMER_FULL_NAME ;
*/




























































