
/*
SELECT DISTINCT
CUSTOMER_UCN,
CUSTOMER_FULL_NAME,
CUSTOMER_SPN,
AGREEMENT_NUMBER
FROM
CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
STATUS_CODE = 'A'
AND AGREEMENT_PROCESSING_STATUS = 'ACTIVE'
AND CUSTOMER_FULL_NAME LIKE 'FIFI%'
--ESCAPE '\'
AND CALCULATION_TYPE = 'DERIVATIVES'
AND NOT EXISTS
(
SELECT
1
FROM
CS_FIREWALL_RULE FW
WHERE
CS_UCN_LEAD_OFFICE = FW.BANK_UCN
AND GROUP_4_VISIBILITY = 'N'
)
ORDER BY
CUSTOMER_FULL_NAME;
*/
/*
SELECT
A.RUN_CATEGORY RUN_CATEGORY,
A.RUN_STATUS RUN_STATUS,
A.RUN_NUMBER RUN_NUMBER,
TO_CHAR(B.COB_DATE,'DD-MON-YYYY') COB_DATE,
TO_CHAR(A.START_DATETIME,'DD-MON-YYYY HH24:MI') START_TIME,
TO_CHAR(A.END_DATETIME,'DD-MON-YYYY HH24:MI') END_TIME ,
REGION REGION
FROM
cs_CMS_RUN_CONTROL A,
CS_RUN_STATUS B
WHERE
A.RUN_NUMBER = B.RUN_NUMBER(+)
---AND B.RUN_TYPE (+) != 'SOD_CEL'
--AND B.run_category(+) = 'INTRA_CEL'
AND B.run_category(+) = 'CFTC_STMT'
*/
/*
SELECT
a.run_number ID,
TO_CHAR (a.start_datetime, 'DD-MON-YYYY HH24:MI') descr
FROM
cs_cms_run_control a
WHERE
a.run_category = 'INTRA_CEL'
AND a.start_datetime =
(
SELECT
MAX (b.start_datetime)
FROM
cs_cms_run_control b
WHERE
b.run_category = 'INTRA_CEL'
AND b.run_status IN ('RUNNING', 'COMPLETED')
);
*/
/*
SELECT
FILE_ID SOURCE_FEED_NAME,
TO_CHAR(MAX(INPUT_DATETIME),'DD-MON-YYYY') FEED_COB,
TO_CHAR(MAX(LOAD_DATETIME),'DD-MON-YYYY HH24:MI') LOAD_TIME,
'' IS_AFTER
FROM
CS_LOAD_STATUS
WHERE
FILE_ID IN
(
SELECT
FILE_ID
FROM
CS_FILE_ID
WHERE
FILE_GROUP IN
(
SELECT
text
FROM
cs_col_texts
WHERE
code='DER_FILE_GROUP'
)
)
AND FILE_ID != 'SCIR5671'
AND LOAD_DATETIME IS NOT NULL
AND INPUT_DATETIME IS NOT NULL
GROUP BY
FILE_ID
ORDER BY
FILE_ID ASC;
*/
/*
SELECT DISTINCT
cs.CUSTOMER_UCN,
cs.CUSTOMER_FULL_NAME,
cs.CUSTOMER_SPN,
cs.AGREEMENT_NUMBER,
gacct.ACCOUNT,
23456 templateId
FROM
CS_COL_CUSTOMER_SETUP cs
LEFT JOIN MO_COMBINED_CUSTOMER_SETUP gmi
ON
(
cs.CUSTOMER_SPN = gmi.CUSTOMER_SPN
OR cs.CUSTOMER_UCN = gmi.CUSTOMER_UCN
)
LEFT JOIN MO_GMI_ACCOUNT_VIEW gacct
ON
(
cs.CUSTOMER_SPN = gacct.CUSTOMER_SPN
)
WHERE
gmi.CUSTOMER_SPN IS NOT NULL;
*/
/*
SELECT DISTINCT
cs.CUSTOMER_UCN,
cs.CUSTOMER_FULL_NAME,
cs.CUSTOMER_SPN,
cs.AGREEMENT_NUMBER
FROM
CS_COL_CUSTOMER_SETUP cs
where rownum < 20;
*/
/*
SELECT DISTINCT
cs.CUSTOMER_UCN,
cs.CUSTOMER_FULL_NAME,
cs.CUSTOMER_SPN,
cs.AGREEMENT_NUMBER,
-- gacct.ACCOUNT,
23456 templateId
FROM
CS_COL_CUSTOMER_SETUP cs
JOIN MO_COMBINED_CUSTOMER_SETUP gmi
ON
(
cs.CUSTOMER_SPN = gmi.CUSTOMER_SPN
OR cs.CUSTOMER_UCN = gmi.CUSTOMER_UCN
)
WHERE
gmi.CUSTOMER_SPN IS NOT NULL;
*/
/*
SELECT DISTINCT
    CUSTOMER_UCN,
    CUSTOMER_FULL_NAME,
    CUSTOMER_SPN
FROM
    CS_COL_CUSTOMER_SETUP CUST_SETUP
WHERE
    STATUS_CODE ='A'
AND AGREEMENT_PROCESSING_STATUS ='ACTIVE'
AND CUSTOMER_SPN LIKE ?
AND CALCULATION_TYPE = ?
AND NOT EXISTS
    (
        SELECT
            1
        FROM
            CS_FIREWALL_RULE FW
        WHERE
            CS_UCN_LEAD_OFFICE = FW.BANK_UCN
        AND GROUP_4_VISIBILITY = 'N'
    )
ORDER BY
    CUSTOMER_FULL_NAME ;
*/




