

DELETE FROM OPS$COAST.CS_CH_FEED
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


INSERT INTO OPS$COAST.CS_CH_FEED
(
    SOURCE_FEED_NAME,
    FEED_FILE_NAME,
    FEED_VALIDATION_TYPE,
    STAGING_TABLE_NAME,
    KEY_COLUMN_NAME,
    COB_COLUMN_NAME,
    CCY_COLUMN_NAME,
    AMOUNT_COLUMN_NAME,
    MTM_COLUMN_NAME,
    UPDATE_DATETIME,
    DATE_COLUMN_POSITION,
    SOURCE_LOCATION,
    TARGET_FILE_NAME,
    TARGET_TABLE_NAME,
    VALIDATE_MULTI_CCY,
    MARGIN_TYPE,
    CLEARING_HOUSE_ID,
    KEY_COLUMN_NAME2,
    SIGN_MULTIPLIER,
    VALIDATION_PROC,
    DOWNLOAD_TIME,
    DOWNLOAD_SCRIPT_NAME,
    STATUS
)
SELECT
    'LCHEMEAIAJPMSL',
    'REP00050c - JPMSL SwapClear Initial Margin_ 1.txt',
    FEED_VALIDATION_TYPE,
    STAGING_TABLE_NAME,
    KEY_COLUMN_NAME,
    COB_COLUMN_NAME,
    CCY_COLUMN_NAME,
    AMOUNT_COLUMN_NAME,
    MTM_COLUMN_NAME,
    sysdate,
    DATE_COLUMN_POSITION,
    'JPL(mbr)/SwapClear/Risk/SwapClear%20Combined%20Margins/Initial%20Margin/REP00050c%20-%20SwapClear%20Initial%20Margin_%201.TXT',
    'REP00050c - JPMSL SwapClear Initial Margin_ 1.TXT',
    TARGET_TABLE_NAME,
    VALIDATE_MULTI_CCY,
    MARGIN_TYPE,
    CLEARING_HOUSE_ID,
    KEY_COLUMN_NAME2,
    SIGN_MULTIPLIER,
    VALIDATION_PROC,
    DOWNLOAD_TIME,
    DOWNLOAD_SCRIPT_NAME,
    STATUS
FROM OPS$COAST.CS_CH_FEED 
WHERE SOURCE_FEED_NAME = 'LCHEMEAIA';


INSERT INTO OPS$COAST.CS_CH_FEED
(
    SOURCE_FEED_NAME,
    FEED_FILE_NAME,
    FEED_VALIDATION_TYPE,
    STAGING_TABLE_NAME,
    KEY_COLUMN_NAME,
    COB_COLUMN_NAME,
    CCY_COLUMN_NAME,
    AMOUNT_COLUMN_NAME,
    MTM_COLUMN_NAME,
    UPDATE_DATETIME,
    DATE_COLUMN_POSITION,
    SOURCE_LOCATION,
    TARGET_FILE_NAME,
    TARGET_TABLE_NAME,
    VALIDATE_MULTI_CCY,
    MARGIN_TYPE,
    CLEARING_HOUSE_ID,
    KEY_COLUMN_NAME2,
    SIGN_MULTIPLIER,
    VALIDATION_PROC,
    DOWNLOAD_TIME,
    DOWNLOAD_SCRIPT_NAME,
    STATUS
)
SELECT
    'LCHEMEAMTMJPMSL',
    'REP00072c - JPMSL Cash Flow and Trade Level NPV_ 1.txt',
    FEED_VALIDATION_TYPE,
    STAGING_TABLE_NAME,
    KEY_COLUMN_NAME,
    COB_COLUMN_NAME,
    CCY_COLUMN_NAME,
    AMOUNT_COLUMN_NAME,
    MTM_COLUMN_NAME,
    sysdate,
    DATE_COLUMN_POSITION,
    'JPL(mbr)/SwapClear/Risk/SwapClear%20Combined%20Margins/Cash%20Settlement/OTC/OTC%20NPVs/REP00072c%20-%20Cash%20Flow%20and%20Trade%20Level%20NPV_%201.TXT',
    'REP00072c - JPMSL Cash Flow and Trade Level NPV_ 1.TXT',
    TARGET_TABLE_NAME,
    VALIDATE_MULTI_CCY,
    MARGIN_TYPE,
    CLEARING_HOUSE_ID,
    KEY_COLUMN_NAME2,
    SIGN_MULTIPLIER,
    VALIDATION_PROC,
    DOWNLOAD_TIME,
    DOWNLOAD_SCRIPT_NAME,
    STATUS
FROM OPS$COAST.CS_CH_FEED 
WHERE SOURCE_FEED_NAME = 'LCHEMEAMTM';


UPDATE OPS$COAST.CS_CH_FEED
SET LCH_PROTOCOL = 'https',
    LCH_SITE = '194.62.172.20/Reporting',
    LCH_USER = 'SWCJPC',
    LCH_PWD = 'MORGAN3456',
    LEGAL_ENTITY = 'JPMCB'
WHERE SOURCE_FEED_NAME like 'LCHEMEA%';


UPDATE OPS$COAST.CS_CH_FEED
SET LCH_USER = 'SWCJPL',
LCH_PWD = 'MORGAN1234',
LEGAL_ENTITY = 'JPMSL'
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


UPDATE OPS$COAST.CS_CH_FEED
SET DOWNLOAD_TIME = '02:00:00'    
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


UPDATE OPS$COAST.CS_CH_FEED
SET DOWNLOAD_TIME = '21:30:00'
WHERE DOWNLOAD_TIME = '21:30';


-- UAT
UPDATE OPS$COAST.CS_CH_FEED
SET DOWNLOAD_LCH_FLAG = 'Y'
WHERE SOURCE_FEED_NAME like 'LCH%';


-- UAT
UPDATE OPS$COAST.CS_CH_FEED
SET LCH_SITE = '194.62.172.34:444/Reporting', 
LCH_USER = 'STSTJPLCLEAR7',
LCH_PWD = 'RCCJPLMO1',
LEGAL_ENTITY = 'JPMSL'
WHERE SOURCE_FEED_NAME = 'LCHEMEAIAJPMSL'
OR SOURCE_FEED_NAME = 'LCHEMEAMTMJPMSL';


COMMIT;

