
logfile-name-prefix=log4j2

Access-Control-Allow-Origin=http://localhost:4200
server-ip-or-fullname=localhost

server.ssl.key-store.file-prefix=lukekeystore
server.ssl.key-store-password=lukema
server.ssl.key-alias=luke

# Must starts with `/c:/D/`
spring.web.resources.static-locations=/c:/D/shein-images
