
logfile-name-prefix=log4j2-linux

Access-Control-Allow-Origin=https://52.3.85.231
server-ip-or-fullname=52.3.85.231

server.ssl.key-store.file-prefix=server
server.ssl.key-store-password=changeme
server.ssl.key-alias=boot

spring.web.resources.static-locations=/shein-images
