# server {
#     listen       80  default_server;
#     listen  [::]:80  default_server;
#     server_name  52.3.85.231;   # !!! Trick: It has to be the fullname of host, or ip address of host, but NOT localhost.
#     return 301 https://${server_name}${request_uri};
# }

server {
    listen       443 ssl;
    # listen  [::]:443 ssl;
    server_name  52.3.85.231;   # !!! Trick: It has to be the fullname of host, or ip address of host, but NOT localhost.
    # server_name  helloebay.com;   # !!! Trick: It has to be the fullname of host, or ip address of host, but NOT localhost.

    # /etc/nginx/ssl will be mounted using
    ssl_certificate      /etc/nginx/ssl/certificate.crt;
    ssl_certificate_key  /etc/nginx/ssl/private.key;

    client_max_body_size 50M;

    # resolver             127.0.0.11;

    #access_log  /var/log/nginx/host.access.log  main;

    location /content {
        add_header X-Frame-Options SAMEORIGIN;

        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $host;
        proxy_pass        https://${server_name}:8443${request_uri};
    }

    location /spring {
        add_header X-Frame-Options SAMEORIGIN;

        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $host;
        proxy_pass        https://${server_name}:8443${request_uri};
    }

    location / {
        add_header X-Frame-Options SAMEORIGIN;

        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header  Host $host;
        proxy_pass        https://${server_name}:9443${request_uri};
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
