server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/lukekeystore.jks
server.ssl.key-store-password=lukema
server.ssl.key-alias=luke
server.port=8443

# Fix of `spring boot tools failed to refresh live data from process`
spring.devtools.livereload.enabled=true

logging.config=classpath:log4j2.xml

# REF: SwaggerConfig.java
#
# Magic fix of:
# Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException:
# Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
# https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
# springfox.documentation.auto-startup=true works for boot 2 (hello 2), but not for boot 3
#     Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.
#                PatternsRequestCondition.getPatterns()" because "this.condition" is null
# springdoc.api-docs.enabled=true is for boot 3
springdoc.api-docs.enabled=true
# springdoc.packagesToScan=com.package1, com.package2
# springdoc.pathsToMatch=/v1, /api/balance/**

# spring.main.allow-circular-references=true

# spring.http.multipart.enabled=true

spring.profiles.active=dev

server.servlet.session.cookie.http-only=true
# strict, lax, none+secure
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

# spring.profiles.active=dev

Access-Control-Allow-Origin=http://localhost:4200
# Access-Control-Allow-Origin=http://server-ip-or-fullname:4200
# Credential is not supported if the CORS header 'Access-Control-Allow-Origin' is '*'
# Access-Control-Allow-Origin=*
# server.servlet.context-path=/nvca-svc

# actuator
# https://localhost:8443/                       ### this is default for spring boot 1
# https://localhost:8443/actuator               ### this is default for spring boot 2
# https://localhost:8443/admin                  ### overriding default
# management.endpoints.web.base-path=/admin    ### overriding default
# spring.security.user.name=user # Default user name.
# spring.security.user.password= # Password for the default user name.
# spring.security.user.roles= # Granted roles for the default user name.

# Swagger 3
# openapi=3.0.0
# components.securitySchemes.bearerAuth.type=http
# components.securitySchemes.bearerAuth.scheme=bearer
# components.securitySchemes.bearerAuth.bearerFormat=JWT
# components.bearerAuth=[]


# by default, it only expose info and health. user comma delimiter. * will expose all 13 endpoints.
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans

# shutdown endpoint is disabled by default
# curl -k -i -X POST https://localhost:8443/actuator/shutdown
management.endpoint.shutdown.enabled=true

# never, authorized, always
management.endpoint.health.show-details=always

# pl.project13.maven:git-commit-id-plugin
management.info.git.mode=full
management.info.java.enabled=false
management.info.env.enabled=true
info.app.name=hello-springboot-app

# Disable security
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

my.property.name=Luke
my.property.age=25

# logging.level.org.springframework=DEBUG

spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
# spring.datasource.url=jdbc:postgresql://localhost:5432/test
# spring.datasource.url=jdbc:hsqldb:hsql://localhost/xdb
# spring.datasource.url=jdbc:hsqldb:hsql://localhost/xdb?createDatabaseIfNotExist=true;sql.syntax_pgs=true
spring.datasource.url=jdbc:hsqldb:hsql://localhost/xdb;sql.syntax_pgs=true
spring.datasource.username=SA
spring.datasource.password=
# spring.datasource.username=ENC(//0WoVkmWvulnznZxey00g==)
# spring.datasource.password=ENC(szibjzsbUyD242hgIAl8Xw==)
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
jasypt.encryptor.algorithm=${JASYPT_ENCRYPTOR_ALGORITHM:}
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

# Hikari
# maximumPoolSize - Default: 10
spring.datasource.hikari.maximumPoolSize=3
# minimumIdle - Default: maximumPoolSize. It is recommanded recommend not setting this value and instead allowing HikariCP
# to act as a fixed size connection pool. Default: same as maximumPoolSize
# spring.datasource.hikari.minimumIdle=3
# idleTimeout - Default: 600000 (10 minutes)
# HikariCP closes and renews connections every 30 minutes (maxLifetime default 1800000 (30 minutes))
spring.datasource.hikari.maxLifetime=1800000
# spring.datasource.connection-init-sql=ALTER SESSION SET CURRENT_SCHEMA=ECOR_OWNER
spring.datasource.hikari.poolName=Luke_Hikari_Pool


spring.datasource.tomcat.initial-size=3
spring.datasource.tomcat.max-active=3
spring.datasource.tomcat.max-age=300000
spring.datasource.tomcat.validation-interval=30000
spring.datasource.tomcat.test-while-idle=true

# spring boot 2. not work for spring boot 3.
## Hibernate Properties
# spring.jpa.open-in-view=false
# spring.data.jpa.repositories.enabled=true
# spring.jpa.generate-ddl=false
# # spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=create
# spring.jpa.show-sql=false

# spring boot 3
# spring.jpa.properties.jakarta.persistence.schema-generation.database.action=create
spring.jpa.properties.jakarta.persistence.schema-generation.database.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.create-database-schemas=true
# spring.jpa.properties.jakarta.persistence.schema-generation.create-database-schemas=false

# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=create
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create-mydb.sql
# spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-source=metadata

spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL

spring.jta.enabled=true

spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm:ss.SSSZ

# Whether a "NoHandlerFoundException" thrown if no Handler was found to process a request:

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

    prop1       =     property 1
   prop2     =     property 2
