server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/@server.ssl.key-store.file-prefix@.jks
server.ssl.key-store-password=@server.ssl.key-store-password@
server.ssl.key-alias=@server.ssl.key-alias@
server.port=8443

# Fix of `spring boot tools failed to refresh live data from process`
spring.devtools.livereload.enabled=true

logging.config=classpath:@logfile-name-prefix@.xml

# REF: SwaggerConfig.java
#
# Magic fix of:
# Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException:
# Cannot invoke "org.springframework.web.servlet.mvc.condition.PatternsRequestCondition.getPatterns()" because "this.condition" is null
# https://stackoverflow.com/questions/70036953/springboot-2-6-0-spring-fox-3-failed-to-start-bean-documentationpluginsboot
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
# springfox.documentation.auto-startup=true works for boot 2 (hello 2), but not for boot 3
#     Caused by: java.lang.NullPointerException: Cannot invoke "org.springframework.web.servlet.mvc.condition.
#                PatternsRequestCondition.getPatterns()" because "this.condition" is null
springfox.documentation.auto-startup=false
# springdoc.api-docs.enabled=true is for boot 3
springdoc.api-docs.enabled=true
# springdoc.packagesToScan=com.package1, com.package2
# springdoc.pathsToMatch=/v1, /api/balance/**

# spring.main.allow-circular-references=true

# spring.http.multipart.enabled=true

server.servlet.session.cookie.http-only=true
# strict, lax, none+secure
server.servlet.session.cookie.same-site=strict
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

# spring.profiles.active=dev

Access-Control-Allow-Origin=@Access-Control-Allow-Origin@
# Access-Control-Allow-Origin=http://localhost
# Access-Control-Allow-Origin=http://server-ip-or-fullname:4200
# Credential is not supported if the CORS header 'Access-Control-Allow-Origin' is '*'
# Access-Control-Allow-Origin=*
# server.servlet.context-path=/nvca-svc

# actuator
# https://@server-ip-or-fullname@:8443/                       ### this is default for spring boot 1
# https://@server-ip-or-fullname@:8443/actuator               ### this is default for spring boot 2
# https://@server-ip-or-fullname@:8443/admin                  ### overriding default
# management.endpoints.web.base-path=/admin    ### overriding default
# spring.security.user.name=user # Default user name.
# spring.security.user.password= # Password for the default user name.
# spring.security.user.roles= # Granted roles for the default user name.

# Swagger 3
# openapi=3.1.1
# components.securitySchemes.bearerAuth.type=http
# components.securitySchemes.bearerAuth.scheme=bearer
# components.securitySchemes.bearerAuth.bearerFormat=JWT
# components.bearerAuth=[]


# by default, it only expose info and health. user comma delimiter. * will expose all 13 endpoints.
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans

# shutdown endpoint is disabled by default
# curl -k -i -X POST https://@server-ip-or-fullname@:8443/actuator/shutdown
management.endpoint.shutdown.access=UNRESTRICTED

# never, authorized, always
management.endpoint.health.show-details=always

# pl.project13.maven:git-commit-id-plugin
management.info.git.mode=full
management.info.java.enabled=false
management.info.env.enabled=true
info.app.name=hello-springboot-app

# Disable security
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

my.property.name=Luke
my.property.age=25

# logging.level.org.springframework=DEBUG

# spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
# spring.datasource.url=jdbc:mysql://@server-ip-or-fullname@:3306/notes_app?useSSL=false
spring.datasource.url=jdbc:postgresql://@server-ip-or-fullname@:5432/test
# spring.datasource.username=luke
# spring.datasource.password=luke
spring.datasource.username=ENC(//0WoVkmWvulnznZxey00g==)
spring.datasource.password=ENC(szibjzsbUyD242hgIAl8Xw==)
# environment var: JASYPT_ENCRYPTOR_PASSWORD=luke-key
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
# environment var: JASYPT_ENCRYPTOR_ALGORITHM=PBEWithMD5AndDES
jasypt.encryptor.algorithm=${JASYPT_ENCRYPTOR_ALGORITHM:}
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

# Hikari
# maximumPoolSize - Default: 10
spring.datasource.hikari.maximumPoolSize=3
# minimumIdle - Default: maximumPoolSize. It is recommanded recommend not setting this value and instead allowing HikariCP
# to act as a fixed size connection pool. Default: same as maximumPoolSize
# spring.datasource.hikari.minimumIdle=3
# idleTimeout - Default: 600000 (10 minutes)
# HikariCP closes and renews connections every 30 minutes (maxLifetime default 1800000 (30 minutes))
spring.datasource.hikari.maxLifetime=1800000
# spring.datasource.connection-init-sql=ALTER SESSION SET CURRENT_SCHEMA=ECOR_OWNER
spring.datasource.hikari.poolName=Luke_Hikari_Pool


spring.datasource.tomcat.initial-size=3
spring.datasource.tomcat.max-active=3
spring.datasource.tomcat.max-age=300000
spring.datasource.tomcat.validation-interval=30000
spring.datasource.tomcat.test-while-idle=true


## Hibernate Properties
spring.jpa.open-in-view=false
spring.data.jpa.repositories.enabled=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# comment out for spring boot 2.7.x to 3.x migration: spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
# spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL

# The SQL dialect makes Hibernate generate better SQL for the chosen database
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.properties.hibernate.ddl-auto=create
# spring.jpa.properties.hibernate.show-sql=false
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.use_sql_comments=true

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jta.enabled=true

###############################################

# spring.application.index= index.html
# spring.application.name= HelloHoustonService

# spring.config.location= # Config file locations.
# spring.config.name=application # Config file name.

spring.mvc.format.date=dd/MM/yyyy
spring.mvc.format.date-time=yyyy-MM-dd'T'HH:mm:ss.SSSZ

# spring.webservices.path=/spring

# spring.batch.job.enabled=false

## JKS_DIR=C:/JavaCAPS/appserver/domains/boot/config
# server.port: 8443
# server.ssl.key-store: ${JKS_DIR:}/bootkeystore.jks
# server.ssl.key-store-password: bootpass
# server.ssl.keyAlias: boot

# server.port: 9101
# server.servlet.contextPath=/rad-svc

# Whether a "NoHandlerFoundException" thrown if no Handler was found to process a request:

###########################################################
################### OAuth2 Google Cloud ###################
###########################################################

spring.security.oauth2.client.registration.google.client-id=155392672886-2tju1pd7516p83gm9no01rb32r8b413e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=QSkTysu_KGQClhTdUQURqHGA
# spring.security.oauth2.client.registration.google.accessTokenUri=https://www.googleapis.com/oauth2/v3/token
# spring.security.oauth2.client.registration.google.userAuthorizationUri=https://accounts.google.com/o/oauth2/auth
# spring.security.oauth2.client.registration.google.tokenName=oauth_token
# spring.security.oauth2.client.registration.google.authenticationScheme=query
# spring.security.oauth2.client.registration.google.clientAuthenticationScheme=form
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri=https://@server-ip-or-fullname@:8443/rest/security/greeting

# spring.security.oauth2.resource.userInfoUri=https://www.googleapis.com/userinfo/v2/me
# spring.security.oauth2.resource.preferTokenInfo=false

# eureka.client.instance.preferIpAddress=true
# eureka.client.serviceUrl.defaultZone=http://@server-ip-or-fullname@:8761/eureka

spring.application.name = eurekaclient

    prop1       =     property 1
   prop2     =     property 2

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# https://@server-ip-or-fullname@:8443/content/luke/java__cert.png

# windows
# !!! Trick: MUST start with `file://`
spring.web.resources.static-locations=file://@spring.web.resources.static-locations@

spring.mvc.static-path-pattern=/content/**

image.url.prefix = https://@server-ip-or-fullname@:8443/content

# Neo4j
# ??? Is uri good? Refer to mongo settings <======== Do **NOT** use uri. jasypt does not work for uri. ???
spring.neo4j.uri=bolt://@server-ip-or-fullname@:7687
# spring.neo4j.authentication.username=neo4j
# spring.neo4j.authentication.password=test@1234
spring.neo4j.authentication.username=ENC(sXvEhQ3NbPRyEeSyUcZkYg==)
spring.neo4j.authentication.password=ENC(HmujZWcdbmtRZcQ0EEgDvnDGeANqKDIM)

# MongoDB
# !!! Trick !!!
# If uri is provided, uri will take presendence or other properties
# (correct with warn! do not use uri, becuase jaspyt does not work.) spring.data.mongodb.uri: mongodb://<username>:<password>@<host>:<port>/<database>
# (correct with warn! do not use uri, becuase jaspyt does not work.) spring.data.mongodb.uri: mongodb://luke:luke@@server-ip-or-fullname@:27017/?authSource=lukedb
# (correct with warn! do not use uri, becuase jaspyt does not work.) spring.data.mongodb.uri: mongodb://luke:luke@@server-ip-or-fullname@:27017/lukedb
# (wrong. jasypt does not work here) spring.data.mongodb.uri: mongodb://ENC(zjpIoh+5DcY+QGRUOxINeA==):ENC(DIM8/d6v+5pS57wfdRfgaA==)@@server-ip-or-fullname@:27017/lukedb
# spring.data.mongodb.uri: mongodb://@server-ip-or-fullname@:27017 <======== Do **NOT** use uri. jasypt does not work for uri.
spring.data.mongodb.host: @server-ip-or-fullname@
spring.data.mongodb.port: 27017
spring.data.mongodb.database: lukedb
# spring.data.mongodb.username: luke
# spring.data.mongodb.password: luke
spring.data.mongodb.username: ENC(zjpIoh+5DcY+QGRUOxINeA==)
spring.data.mongodb.password: ENC(DIM8/d6v+5pS57wfdRfgaA==)
