
my.properties.name= Luke Ma
my.properties.name= Luke Ma 2

# This value will be overriden by the last line which sets the value.
my.properties.age=28

# The latest value will win.
my.properties.age=27


