/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation(libs.guava)
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use JUnit Jupiter test framework
            useJUnitJupiter("5.10.0")
        }
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(23)
    }
}

application {
    // Define the main class for the application.
    mainClass = "com.learn.App"
}

tasks.register("hello") {
    group = "Custom"
    description = "A lovely greeting task."

    doLast {
        println("Hello world! I am hello.")
    }

    dependsOn(tasks.assemble)
}

tasks.register("intro") {
    doLast {
        println("I'm Intro")
    }

    dependsOn("hello")
}

tasks.register("taskX") {
    dependsOn("taskY")
    doLast {
        println("taskX")
    }
}

tasks.register("taskY") {
    doLast {
        println("taskY")
    }
}

repeat(4) { counter ->
    tasks.register("task$counter") {
        doLast {
            println("I'm task number $counter")
        }
    }
}

tasks.named("task0") { dependsOn("task2", "task3") }

tasks.named("hello") {
    doFirst {
        println("Hello doFirst")
    }
}

tasks.named("hello") {
    doLast {
        println("Hello doLast1")
    }
}

// the actions in the action list are executed in order.
tasks.named("hello") {
    doLast {
        println("Hello doLast2")
    }
}


/**
 * gradle -q hello2
 * gradle help --task hello2
 */

// Extend the DefaultTask class to create a HelloTask class
abstract class HelloTask : DefaultTask() {
    @TaskAction
    fun hello() {
        println("hello from HelloTask")
    }
}

// Register the hello Task with type HelloTask
tasks.register<HelloTask>("hello2") {
    group = "Custom tasks"
    description = "A lovely greeting task."
}

tasks.register("hello3") {
   doLast {
      val ver="1.2.3"
      println("hello ${ver}")
   }
}

