<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>com.learn</groupId>

   <artifactId>ThreadRestart</artifactId>

   <packaging>jar</packaging>

   <version>1.0</version>

   <name>ThreadRestart</name>

   <dependencies>
      <dependency>
         <groupId>log4j</groupId>

         <artifactId>log4j</artifactId>

         <version>1.2.14</version>
      </dependency>

      <dependency>
         <groupId>junit</groupId>

         <artifactId>junit</artifactId>

         <version>4.4</version>

         <scope>test</scope>
      </dependency>
   </dependencies>
</project>
