apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-statefulset
  namespace: efk-logging
spec:
  serviceName: elasticsearch-service
  replicas: 2
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: cluster.name
              value: k8s-logs
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: "elasticsearch-statefulset-0.elasticsearch-service,elasticsearch-statefulset-1.elasticsearch-service"
            - name: cluster.initial_master_nodes
              value: "elasticsearch-statefulset-0,elasticsearch-statefulset-1"
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
