
/**
 * Why would a JavaScript variable start with a dollar sign?
 *
 * 1. A very common use in jQuery is to distinguish jQuery objects stored in variables from other variables. For example,
 *
 *       var $email = $("#email"); // refers to the jQuery object representation of the dom object
 *       var emailField = $("#email").get(0); // refers to the dom object itself
 *       var $this = $(this);
 *
 *    This is very helpful in writing jQuery code and makes it easy to see jQuery objects which have a different set of properties.:w
 *
 * 2. In the 1st, 2nd, and 3rd Edition of ECMAScript, using $-prefixed variable names was explicitly discouraged by the spec except
 *    in the context of autogenerated code:
 *
 *       The dollar sign ($) and the underscore (_) are permitted anywhere in an identifier. The dollar sign is intended for use
 *       only in mechanically generated code.
 *
 *    However, in the next version (the 5th Edition, which is current), this restriction was dropped, and the above passage replaced with:
 *
 *       The dollar sign ($) and the underscore (_) are permitted anywhere in an IdentifierName.
 *
 *    As such, the $ sign may now be used freely in variable names.
 *
 * 3. In the context of AngularJS, the $ prefix is used only for identifiers in the framework's code. Users of the framework are
 *    instructed not to use it in their own identifiers:
 *
 *       Angular Namespaces $ and $$
 *       To prevent accidental name collisions with your code, Angular prefixes names of public objects with $ and names of private
 *       objects with $$. Please do not use the $ or $$ prefix in your code.
 *
 *    Source: https://docs.angularjs.org/api
 *
 * */

const $form = 'Hello World.';
console.log($form);

const $$this = 'This is is a private object in Angular.';

console.log($$this);



