

org.quartz.scheduler.instanceName = MyScheduler
org.quartz.jobListener.myJobListener.class=com.learn.listener.MyJobListener
org.quartz.plugin.jobInitializer.fileNames = myjobs.xml

org.quartz.threadPool.threadCount = 3
org.quartz.plugin.jobInitializer.class = org.quartz.plugins.xml.XMLSchedulingDataProcessorPlugin
org.quartz.plugin.jobInitializer.failOnFileNotFound = true
org.quartz.plugin.jobInitializer.scanInterval = 10
org.quartz.plugin.jobInitializer.wrapInUserTransaction = false

