<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
   <modelVersion>4.0.0</modelVersion>

   <groupId>com.co.learn</groupId>

   <artifactId>ConnectionPool</artifactId>

   <packaging>jar</packaging>

   <version>1.0</version>

   <dependencies>
      <dependency>
         <groupId>com.microsoft.jdbc.base</groupId>

         <artifactId>msbase</artifactId>

         <version>2.2</version>
      </dependency>

      <dependency>
         <groupId>com.microsoft.jdbc.sql</groupId>

         <artifactId>mssqlserver</artifactId>

         <version>2.2</version>
      </dependency>

      <dependency>
         <groupId>com.microsoft.jdbc.util</groupId>

         <artifactId>msutil</artifactId>

         <version>2.2</version>
      </dependency>

      <dependency>
         <groupId>com.co.messaging</groupId>

         <artifactId>MessagingUtilities</artifactId>

         <version>1.0</version>
      </dependency>

      <dependency>
         <groupId>junit</groupId>

         <artifactId>junit</artifactId>

         <version>3.8.1</version>

         <scope>test</scope>
      </dependency>
   </dependencies>
</project>
