<project xmlns="https://maven.apache.org/POM/4.0.0" xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="https://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>EJB3JBoss-packaging</artifactId>
	<name>${project.artifactId}</name>
	<packaging>ear</packaging>

	<parent>
		<groupId>com.learn</groupId>
		<artifactId>EJB3JBoss-Basic</artifactId>
		<version>1.0</version>
	</parent>

	<properties>
		<jboss_deploy.dir>${env.JBOSS_HOME}/server/default/deploy</jboss_deploy.dir>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.learn</groupId>
			<artifactId>EJB3JBoss-ejbs</artifactId>
			<version>1.0</version>
			<type>ejb</type>
		</dependency>
		<dependency>
			<groupId>com.learn</groupId>
			<artifactId>EJB3JBoss-web</artifactId>
			<version>1.0</version>
			<type>war</type>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-ear-plugin</artifactId>
				<version>2.7</version>
				<configuration>
					<archive>
						<addMavenDescriptor>false</addMavenDescriptor>
					</archive>
					<outputDirectory>${jboss_deploy.dir}</outputDirectory>
					<modules>
						<!-- <javaModule> <groupId>org.jboss.el</groupId> <artifactId>jboss-el</artifactId>
							<includeInApplicationXml>false</includeInApplicationXml> <bundleDir>lib</bundleDir>
							</javaModule> -->
						<javaModule>
							<groupId>log4j</groupId>
							<artifactId>log4j</artifactId>
							<includeInApplicationXml>false</includeInApplicationXml>
							<bundleDir>lib</bundleDir>
						</javaModule>
						<webModule>
							<groupId>com.learn</groupId>
							<artifactId>EJB3JBoss-web</artifactId>
							<contextRoot>/EJB3-ROOT</contextRoot>
						</webModule>
					</modules>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
