

spring.datasource.url= jdbc:postgresql://localhost:5432/test 

spring.datasource.username=luke
spring.datasource.password=luke

# spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.DB2Dialect
# spring.jpa.properties.hibernate.ddl-auto = none

spring.jpa.properties.hibernate.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.mvc.date-format= dd/MM/yyyy

spring.batch.job.enabled = false



