package com.myprject.plugin.java;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.project.MavenProject;

import java.util.*;
import java.io.*;

/**
 * @goal fixc
 * @description Fix src, resources, output paths generated by mvn eclipse:eclipse
 * to change 
 *       <classpathentry kind="src" path="D:/04-workspace/welldap_x_esp_module/welldap_x_esp/src />
 * into 
 *       <classpathentry kind="src" path="welldap_x_esp/src />
 */
public class FixMvnEclipseClasspathMojo 
extends AbstractMojo 
{
   /**
   * @parameter expression="${basedir}" default-value="${basedir}"
   */
   private String basedir;

   /**
   * Set this value in pom.xml properties:
   *    <properties>
   *       <my.eclipse.workspace>${env.WORKSPACE}</my.eclipse.workspace>
   *    </properties>
   * or in command line:
   *    -Declipse.workspace.string.to.remove=D:/04-workspace
   *
   * @parameter expression="${my.eclipse.workspace}"
   * @required
   * @readonly
   */
   private String workspace;

   private static final String IN_FILE_NAME  = ".classpath";


   public void execute() throws MojoExecutionException 
   {
      workspace = formatWorkspace(workspace); 

      File basedirFile = new File(basedir);

      getLog().info("Eclipse workspace: " + workspace);
      getLog().info("Basename:          " + basedirFile.getName());
      getLog().info("File to fix:       " + IN_FILE_NAME);

      File inFile = new File(basedir, IN_FILE_NAME);
      if (!inFile.exists())
      {
         getLog().info("File not exists.");
         getLog().info("Run 'mvn eclipse:clean eclipse:eclipse' to generate the file.");
         return;
      }

      try
      {
         if (!shouldFix(inFile))
         {
            getLog().info("File not modified.");
            return;
         }

         fixFile(inFile);
      }
      catch (Throwable t)
      {
         t.printStackTrace();
         throw new MojoExecutionException(t.getMessage());
      }
   }

   private String formatWorkspace(String str)
   {
      while (str.indexOf('\\') > 0)
      {
         str = str.replace('\\', '/');
      }

      if (str.indexOf(":/") == 1)
      {
         str = str.substring(0, 1).toUpperCase() + str.substring(1);
      }

      return str;
   }

   public void fixFile(File inFile) 
   throws IOException 
   {
      getLog().info("Fixing file...");

      String tmpFileName = ".classpath-tmp";
      File tmpFile = new File(basedir, tmpFileName);

      FileReader fr = null;
      FileWriter fw = null;

      BufferedReader br = null;
      BufferedWriter bw = null;

      try
      {
         fr = new FileReader(inFile);
         fw = new FileWriter(tmpFile, false);

         br = new BufferedReader(fr);
         bw = new BufferedWriter(fw);

         for (String line = br.readLine(); line != null; line = br.readLine())
         {
            int index = line.indexOf(workspace);
            if (index > 0)
            {
               int nextIndex = line.indexOf("/", index + workspace.length() + 1);

               if (nextIndex > index)
               {
                  String partA = line.substring(0, index);
                  String partB = line.substring(nextIndex + 1);

                  line = partA + partB;
               }
            }

            bw.write(line);
            bw.newLine();
         }

         bw.flush();

         getLog().info(IN_FILE_NAME + " has been fixed.");
      }
      finally
      {
         if (br != null)
         {
            br.close();
         }

         if (bw != null)
         {
            bw.close();
         }

         if (fw != null)
         {
            fw.close();
         }

         if (fr != null)
         {
            fr.close();
         }
      }

      inFile.delete();
      tmpFile.renameTo(inFile);
   }

   public boolean shouldFix(File inFile)
   throws IOException 
   {
      getLog().info("Checking if the file needs fix...");

      FileReader fr = null;
      BufferedReader br = null;

      try
      {
         fr = new FileReader(inFile);
         br = new BufferedReader(fr);

         for (String line = br.readLine(); line != null; line = br.readLine())
         {
            int index = line.indexOf(workspace);
            if (index > 0)
            {
               getLog().info("Workspace:    " + workspace);

               int nextIndex = line.indexOf("/", index + workspace.length() + 1);

               if (nextIndex > index)
               {
                  String partA = line.substring(0, index);
                  String partB = line.substring(nextIndex + 1);

                  String newString = partA + partB;

                  String moduleName = line.substring(index + workspace.length() + 1, nextIndex);
                  getLog().info("Modeule name: " + moduleName);

                  return true;
               }
               else
               {
                  getLog().error("Found a line with workspace name but no module name: " + line);
                  getLog().error("Check the file.");

                  return false;
               }
            }
         }
      }
      finally
      {
         if (br != null)
         {
            br.close();
         }

         if (fr != null)
         {
            fr.close();
         }
      }

      getLog().info("File is good. No need to fix.");

      return false;
   }
}

