

handlers = java.util.logging.ConsoleHandler
#handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler
#handlers = java.util.logging.FileHandler

.level = FINEST

#java.util.logging.FileHandler.pattern = target/log%g.txt
#java.util.logging.FileHandler.limit = 50000
#java.util.logging.FileHandler.count = 3
#java.util.logging.FileHandler.formatter = java.util.logging.XMLFormatter
#java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter
#java.util.logging.FileHandler.formatter = com.learn.jul.util.MyLogFormatter

#java.util.logging.ConsoleHandler.level = ALL
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter

#MyLogFormatter failed to read parameterized logging.
#java.util.logging.ConsoleHandler.formatter = com.learn.jul.util.MyLogFormatter


#com.learn.level = FINEST 
