xsp-list=sboxxs1.adpt-tech.net,sboxxs2.adpt-tech.net
address_change_request_url=Overrided value
address_change_status_url=http://verizon-qa.broadcloudpbx.net/e911address/async/status?tn=%s&amp;eventFilter=%s
