
# spring.cloud.function.scan.packages=com.learn.serverless

# spring.cloud.function.definition

##########################
# Put these in appliation.properties file or java command line args.
# Or, in lambda function environment variable, define FUNCTION_NAME=transform
##########################
# spring.cloud.function.definition=reverse;greeting3;getBook;transform
# spring.cloud.function.definition=reverse|greeting3|getBook|transform
spring.cloud.function.definition=transform
# spring.cloud.function.definition=getBooks
# spring.cloud.function.definition=getBooks|getBooksByName|addBook|deleteBook|reverse|greeting3|transform
