# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://app.vagrantup.com/boxes/search
  # config.vm.box = "base"
  # config.vm.box = "bento/centos-8.5"
  # config.vm.box = "bento/centos-7.6"
  # config.vm.box = "ubuntu/trusty64"
  # config.vm.box = "ubuntu/xenial64"
  # config.vm.box = "ubuntu/focal64"
  config.vm.box = "bento/ubuntu-20.04"
  # The only working ubuntu version are "bento/ubuntu-16.04" and "ubuntu/trusty64". Other versions have "ssh timeout error".
  # config.vm.box = "bento/ubuntu-16.04"
  # config.vm.box = "hashicorp/bionic64"
  #
  # Official Box: HashiCorp (the makers of Vagrant) publish a basic Ubuntu 18.04 64-bit box that is available for minimal use cases.
  # It is highly optimized, small in size, and includes support for VirtualBox, Hyper-V, and VMware.
  # For other users, we recommend the Bento boxes. The Bento boxes are open source and built for a number of providers
  # including VMware, VirtualBox, and Parallels.
  # config.vm.box = "hashicorp/bionic64"
  config.vm.provision :shell, path: "bootstrap.sh"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = true

  # This section is optional: config.vm.network "forwarded_port"
  # 
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest(vagrant) machine.
  # 
  # host: windows 10 laptop
  # guest: vagrant virtual box
  # windows localhost:8080 will be forwarded to lukevm:80
  # config.vm.network "forwarded_port", guest: 80, host: 8080  
  #
  # config.vm.network "forwarded_port", guest: 22, host: 2223, host_ip: "127.0.0.1", id: 'ssh'

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # This should be a different subnet from the laptop subnet. Laoptop subnet is now 192.168.1.*
  # 192.168.3.1 Default Router IP Login. Reserved. Do not use.
  config.vm.network "private_network", ip: "192.168.1.101"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder "D:/03-lukema/git/tfc", "/u1/tfc"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #  vb.memory = "4096"
    vb.memory = "2048"
    vb.name = "lukevm_test"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
