
# Maven resources filtering interpolation
# https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.3-Release-Notes#maven-resources-filtering
# If you use the spring-boot-starter-parent, Maven tokens are only filtered using 
# @ now. This prevents any Spring placeholders in your configuration (e.g. ${foo}) 
# to be be expanded by the build.
# Concretely, if you are still using the standard format (i.e. ${project.version}) 
# please migrate them (@project.version@) or override the maven-resources-plugin configuration.

# spring.profiles.active=@spring.profiles.active@
# Not: spring.profiles.active=${spring.profiles.active} --- If use spring-boot-starter-parent

spring.profiles.active=development

spring.jms.pub-sub-domain=true

# spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.broker-url=tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
# spring.activemq.broker-url=vm://embedded?broker.persistent=false,useShutdownHook=false
spring.activemq.user=admin
spring.activemq.password=secret

# spring.activemq.in-memory=true
# spring.activemq.pool.enabled=false
# spring.activemq.pool.max-connections=50


