/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.learn;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        App app = new App();

        System.out.println("================: " + app.getGreeting());

        assertNotNull(app.getGreeting(), "app should have a greeting");
    }
}
