spring.application.name=a-bootiful-client

# Actuator
# management.info.env.enabled=true
# by default, it only expose info and health. user comma delimiter. * will expose all 13 endpoints.
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=beans
# management.endpoints.web.exposure.include=health,info,env,beans
# management.endpoints.jmx.exposure.include=health,info,env,beans
# shutdown endpoint is disabled by default
# curl -X POST http://localhost:8080/actuator/shutdown
management.endpoint.shutdown.enabled=false
# never, authorized, always
management.endpoint.health.show-details=always
