cucumber.ansi-colors.disabled=true
cucumber.plugin=pretty

# glue is a list of Step definition classes or Step package names .
# Step class names also work
# cucumber.glue=com.learn.cucumber.test, com.learn.cucumber.test.
# glue is a list of Step definition classes or Step package names 
# Step class names also work
# cucumber.glue=com.learn.cucumber.test.StepDefinitions, com.learn.cucumber.test.HelloCucumberSteps

# features are a list of feature files or feature file folders.
# cucumber.features=src/it/resources/com/learn/cucumber/test/hello-cucumber.feature
cucumber.features=src/it/resources/com/learn/cucumber/test, src/it/resources/com/learn/selenium/test
# cucumber.features=src/it/resources/com/learn/cucumber/test/is-it-friday-yet.feature
# cucumber.features=src/it/resources/com/learn/selenium/test/google-search.feature


# cucumber.ansi-colors.disabled=  # true or false. default: false                     
# cucumber.execution.dry-run=     # true or false. default: false 
# cucumber.execution.limit=       # number of scenarios to execute (CLI only).  
# cucumber.execution.order=       # lexical, reverse, random or random:[seed] (CLI only). default: lexical
# cucumber.execution.strict=      # true or false. default: true.
# cucumber.execution.wip=         # true or false. default: false.
# cucumber.features=              # command separated paths to feature files. example: path/to/example.feature, path/to/other.feature  
# cucumber.filter.name=           # regex. example: .*Hello.*
# cucumber.filter.tags=           # tag expression. example: @smoke and not @slow 
# cucumber.glue=                  # comma separated package names. example: com.example.glue  
# cucumber.plugin=                # comma separated plugin strings. example: pretty, json:path/to/report.json
# cucumber.object-factory=        # object factory class name. example: com.example.MyObjectFactory
# cucumber.snippet-type=          # underscore or camelcase. default: underscore

