services:
  myproperties-lma:
    image: khipu/openjdk17-alpine:latest
    container_name: myproperties-lma
    restart: no
    volumes:
      - ./target/my-properties-boot.war:/my-properties-boot.war:ro
    ports:
      - 8443:8443
    networks:
      - net-lma
    command: ["java", "-jar", "my-properties-boot.war"]

networks:
  net-lma:
    external: false
    name: lukenet-lma
