FROM openjdk:19-jdk-alpine3.16

EXPOSE 8443

# Do not run mvn build in docker buildx build. Unable to find mvn command.
# run: mvn -P k8s -Dmaven.test.skip=true clean package
ADD target/my-properties-boot.war my-properties-boot.war

# Optional
# RUN mkdir -p /home/lma/logs

ENTRYPOINT ["java", "-jar", "my-properties-boot.war"]
