apiVersion: v1
kind: ConfigMap
metadata:
  # namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      # - 10.116.200.220-10.116.200.250
      - 192.168.1.201-192.168.1.220
