server.servlet.context-path=/hello-mongodb-boot
spring.application.name=hello-mongodb-boot
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.username=ENC(zjpIoh+5DcY+QGRUOxINeA==)
spring.data.mongodb.password=ENC(DIM8/d6v+5pS57wfdRfgaA==)
spring.data.mongodb.database=lukedb
spring.profiles.active=local
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
jasypt.encryptor.algorithm=${JASYPT_ENCRYPTOR_ALGORITHM:}
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator

