
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=### %d{yyyy-MM-dd HH:mm:ss} %-5p %C(%L) %M() %n%m%n

log4j.appender.com=org.apache.log4j.RollingFileAppender
log4j.appender.com.File=logs/myLogFile.txt
log4j.appender.com.Append=false
log4j.appender.com.MaxFileSize=2MB
log4j.appender.com.MaxBackupIndex=4
log4j.appender.com.layout=org.apache.log4j.PatternLayout
log4j.appender.com.layout.ConversionPattern=### %d{yyyy-MM-dd HH:mm:ss} %-5p %C(%L) %M() %n%m%n

log4j.logger.com=debug

log4j.rootLogger=debug, stdout, com


