/**
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.learn;

import org.springframework.boot.autoconfigure.SpringBootApplication;

@Log4j2
@SpringBootApplication
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("================: " + new App().getGreeting());
    }

    public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
  }

  @Bean
  public CommandLineRunner commandLineRunner(ApplicationContext ctx) {
    return args -> {

      log.info("==================================== Boot Starting {}... ====================================",
                () -> Application.class.getSimpleName());

      String[] beanNames = ctx.getBeanDefinitionNames();
      Arrays.sort(beanNames);
      for (String beanName : beanNames) {
        log.info(() -> beanName);
      }

      log.info("====================================== Boot Started {} ======================================",
                () -> Application.class.getSimpleName());

    };
  }
}
