# logging.config=classpath:logback-file.xml

spring.profiles.active=dev

server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.timeout=30m

# spring.profiles.active=dev

Access-Control-Allow-Origin=http://localhost:4200
# server.servlet.context-path=/nvca-svc

# Disable security
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

my.property.name=Luke
my.property.age=25

# logging.level.org.springframework=DEBUG

# spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
# spring.datasource.url=jdbc:mysql://localhost:3306/notes_app?useSSL=false
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=luke
spring.datasource.password=ENC(P3Tt8KdEzfU5+YWwHatbvA==)
# environment var: JASYPT_ENCRYPTOR_PASSWORD=luke-key
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD:}
# environment var: JASYPT_ENCRYPTOR_ALGORITHM=PBEWithMD5AndDES
jasypt.encryptor.algorithm=${JASYPT_ENCRYPTOR_ALGORITHM:}

# Hikari
# maximumPoolSize - Default: 10
spring.datasource.hikari.maximumPoolSize=3
# minimumIdle - Default: maximumPoolSize. It is recommanded recommend not setting this value and instead allowing HikariCP
# to act as a fixed size connection pool. Default: same as maximumPoolSize
# spring.datasource.hikari.minimumIdle=3
# idleTimeout - Default: 600000 (10 minutes) 
# HikariCP closes and renews connections every 30 minutes (maxLifetime default 1800000 (30 minutes))
spring.datasource.hikari.maxLifetime=1800000
# spring.datasource.connection-init-sql=ALTER SESSION SET CURRENT_SCHEMA=ECOR_OWNER
spring.datasource.hikari.poolName=Luke_Hikari_Pool


spring.datasource.tomcat.initialSize=3
spring.datasource.tomcat.maxTotal=3
spring.datasource.tomcat.maxActive=3
spring.datasource.tomcat.maxAge=300000
spring.datasource.tomcat.validationInterval=30000
spring.datasource.tomcat.testWhileIdle=true


## Hibernate Properties
spring.data.jpa.repositories.enabled=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
# spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# The SQL dialect makes Hibernate generate better SQL for the chosen database
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL9Dialect

# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.properties.hibernate.ddl-auto=create
# spring.jpa.properties.hibernate.show-sql=false
# spring.jpa.properties.hibernate.format_sql=true
# spring.jpa.properties.hibernate.use_sql_comments=true

# spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jta.enabled=true

###############################################

# spring.application.index= index.html
# spring.application.name= HelloHoustonService

# spring.config.location= # Config file locations.
# spring.config.name=application # Config file name.

spring.mvc.date-format= dd/MM/yyyy

# spring.webservices.path=/spring

spring.batch.job.enabled=false

## JKS_DIR=C:/JavaCAPS/appserver/domains/boot/config
# server.port: 8443
# server.ssl.key-store: ${JKS_DIR:}/bootkeystore.jks
# server.ssl.key-store-password: bootpass
# server.ssl.keyAlias: boot

# server.port: 9101
# server.servlet.contextPath=/rad-svc

# Whether a "NoHandlerFoundException" thrown if no Handler was found to process a request:
spring.mvc.throw-exception-if-no-handler-found=true 

