# Short: https://docs.mongodb.com/manual/administration/configuration/ 
# Full:  https://docs.mongodb.com/manual/reference/configuration-options/
#
security:
   authorization: enabled
# setParameter:
#    enableLocalhostAuthBypass: false
net:
#   bindIp: 127.0.0.1,192.168.1.100,10.8.0.10
   bindIp: 127.0.0.1
   port: 27017
storage:
   dbPath: D:/MongoDB/data/db
systemLog:
   destination: file
   path: "D:/MongoDB/log/mongod.log"
   logAppend: true
storage:
   journal:
      enabled: true
processManagement:
   pidFilePath: D:/MongoDB/db0.pid
   
   
   
   
   
   
